

(function(){'use strict';function Qc(a,b){return new ea(a,b)}function B(a,b){for(var c in a)if(J(a,c)&&!1===b.call(a,a[c],c,a))break}function Rc(a){function b(e,f,g){L(d,e,function(h,k,l){h=ec(h,k,l);Ce(d,h.methods,f,g,h.w);return d})}var c="Object"===a,d=Sc(a,!0);b("defineStatic",1);b("defineInstance",2);b("defineInstanceAndStatic",3);b("defineStaticWithArguments",1,!0);b("defineInstanceWithArguments",2,!0);L(d,"defineStaticPolyfill",function(e,f,g){e=ec(e,f,g);Cb(Va[a],e.methods,!0,e.w);return d});L(d,"defineInstancePolyfill",
function(e,f,g){e=ec(e,f,g);Cb(Va[a].prototype,e.methods,!0,e.w);B(e.methods,function(h,k){Db(d,k,h)});return d});L(d,"alias",function(e,f){var g=d,h="string"===typeof f?d[f]:f;g[e]=h;h.instance&&Db(g,e,h.instance,!0);return d});L(d,"extend",function(e){function f(q,t){var x=e[q];if(x)for(var v=0,u;u=x[v];v++)if(u===t)return!0;return!1}function g(q,t){return e[q]&&!f(q,t)}function h(q,t,x){var v;if(v=!(c&&x===l&&(!Tc||"get"===q||"set"===q))){a:if(t=t.flags,x[q]&&t){for(x=0;x<t.length;x++)if(!1===
e[t[x]]){x=!0;break a}x=void 0}else x=!1;v=!x}return v&&!f("except",q)}var k=Va[a],l=k.prototype,m={},n={};e=e||{};var p=e.methods;if(!f("except",k)&&!g("namespaces",k))return c&&"boolean"===typeof e.objectPrototype&&(Tc=e.objectPrototype),B(p||d,function(q,t){p&&(t=q,q=d[t]);J(q,"instance")&&h(t,q,l)&&(n[t]=q.instance);J(q,"static")&&h(t,q,k)&&(m[t]=q)}),Cb(k,m),Cb(l,n),p||L(d,"active",!0),d});Eb[a]=d;Uc["[object "+a+"]"]=d;Fb(a);De(d);return C[a]=d}function Ee(){return"Sugar"}function Ce(a,b,c,
d,e){B(b,function(f,g){var h=f;d&&(h=Vc(f));e&&(h.flags=e);if(c&2&&!f.instance){var k=d?Vc(f,!0):Fe(f);L(h,"instance",k)}c&1&&L(h,"static",!0);k=h;a[g]=k;k.instance&&Db(a,g,k.instance,!0);a.active&&a.extend(g)})}function ec(a,b,c){if("string"===typeof a){var d={};d[a]=b;a=c}else d=a,a=b;return{w:a,methods:d}}function Vc(a,b){var c=a.length-1-(b?1:0);return function(){var d=[],e=[];b&&d.push(this);var f=Math.max(arguments.length,c);for(var g=0;g<f;g++)g<c?d.push(arguments[g]):e.push(arguments[g]);
d.push(e);return a.apply(this,d)}}function Fe(a){switch(a.length){case 0:case 1:return function(){return a(this)};case 2:return function(b){return a(this,b)};case 3:return function(b,c){return a(this,b,c)};case 4:return function(b,c,d){return a(this,b,c,d)};case 5:return function(b,c,d,e){return a(this,b,c,d,e)}}}function Cb(a,b,c,d){B(b,function(e,f){c&&!d&&a[f]||L(a,f,e)})}function Sc(a){function b(c,d){if(!(this instanceof b))return new b(c,d);this.constructor!==b&&(c=this.constructor.apply(c,
arguments));this.raw=c}L(b,"toString",function(){return"Sugar"+a});L(b.prototype,"valueOf",function(){return this.raw});return b}function Db(a,b,c){c=Ge(c);var d;var e=Wc.prototype;var f=(d=e[b])&&d!==Object.prototype[b];d&&d.N||(e[b]=f?He(b):c);a.prototype[b]=c;a===C.Object&&Ie(b,c)}function De(a){B(C.Object&&C.Object.prototype,function(b,c){if("function"===typeof b){var d=a.prototype;J(d,c)||(d[c]=b)}})}function Ie(a,b){B(Eb,function(c){c=c.prototype;J(c,a)||(c[a]=b)})}function Ge(a){return function(){return new Wc(a.apply(this.raw,
arguments))}}function He(a){function b(){var c=this.raw,d;null!=c&&(d=Uc[ka(c)]);d||(d=C.Object);return(new d(c))[a].apply(this,arguments)}b.N=!0;return b}function Fb(a,b){var c=Eb[a],d=Va[a].prototype;!b&&Xc&&(b=Xc(d));B(b,function(e){if("constructor"!==e&&"valueOf"!==e&&"__proto__"!==e){try{var f=d[e];if("function"!==typeof f)return}catch(g){return}Db(c,e,f)}})}function Je(a,b,c){a[b]=c.value}function L(a,b,c,d){Gb(a,b,{value:c,enumerable:!!d,configurable:!0,writable:!0})}function ka(a){return fc.call(a)}
function J(a,b){return!!a&&Ke.call(a,b)}function A(a,b){if(J(a,b))return a[b]}function Hb(a,b,c){c||(c=ka(a));return c==="[object "+b+"]"}function Na(a){return function(b,c,d){b[a](c,d)}}function Wa(a,b,c,d){T(a,Yc(b,c),d)}function Le(a,b,c,d){gc(a,Yc(b,c),d)}function Yc(a,b){var c={};F(a)&&(a=ua(a));D(a,function(d,e){b(c,d,e)});return c}function va(a){function b(c){var d=arguments;return a(c,d[1],d[2],d.length-1)}b.instance=function(c){var d=arguments;return a(this,c,d[1],d.length)};return b}function Zc(a,
b,c){L(a,b,c)}function hc(a,b){function c(e){return d[e]}var d=oa({},b);L(a,"getOption",c);Zc(a,"setOption",function(e,f){if(1===arguments.length)var g=e;else g={},g[e]=f;B(g,function(h,k){null===h&&(h=b[k]);d[k]=h})});return c}function $c(a,b){var c=a.prototype;B(b,function(d,e){c[e]=d})}function ad(a){if(!a)throw new TypeError("Argument required");}function la(a){if(!U(a))throw new TypeError("Function is not callable");}function Oa(a){a=+a||0;if(0>a||!R(a)||!isFinite(a))throw new RangeError("Invalid number");
return Z(a)}function w(a){return void 0!==a}function E(a){return void 0===a}function mb(a){var b="_sugar_"+a;return function(c,d){return 1<arguments.length?(L(c,b,d),c):c[b]}}function bd(a,b){a.prototype.constructor=function(){return b.apply(this,arguments)}}function wa(a){if(!Ea(a)){var b=ka(a);if(xa(a,b))return Me(a);if(ia(a,b))return Ne(a);if(U(a,b))return Oe(a);if(Ib(a,b))return Pe(a)}return Qe(a)}function Pe(a){var b={};return function(c,d,e){var f=!0;if(!V(c))return!1;B(a,function(g,h){b[h]=
A(b,h)||wa(g);!1===b[h].call(e,c[h],d,e)&&(f=!1);return f});return f}}function Qe(a){return function(b){return Pa(b,a)}}function Me(a){a=RegExp(a);return function(b){return a.test(b)}}function Ne(a){var b=a.getTime();return function(c){return!(!c||!c.getTime)&&c.getTime()===b}}function Oe(a){return function(b,c,d){return b===a||a.call(d,b,c,d)}}function Jb(a,b,c){return Xa(a,b,c,!1)}function Xa(a,b,c,d,e,f,g){var h=a||void 0;if(null!=b){if(V(b))a=[b];else{b=String(b);if(-1!==b.indexOf(".."))return Re(a,
b,c,g);a=b.split("[")}var k=w(g);for(var l=0,m=a.length;l<m;l++){var n=a[l];F(n)&&(n=n.split("."));for(var p=0,q=n.length;p<q;p++){b=n[p];var t=l===m-1&&p===q-1;var x=b.indexOf("]");var v=-1!==x;var u=k&&0===x;x=1<m&&p===q-1;u?b=h.length:v&&(b=b.slice(0,-1));v&&0>b&&(b=+b+h.length);if(l||b||1===m)if(v=c?b in h:J(h,b),!e||t&&!f||v){if(d){if(t||!v)return v}else if(k&&t){if(Ea(h))throw new TypeError("Property cannot be written");h[b]=g}h=v?h[b]:void 0}else h=h[b]=x||f&&t?[]:{}}}return h}}function Re(a,
b,c,d){var e,f;if(e=b.match(Se)){b=w(d);a=(f=e[1])?Xa(a,f,c,!1,b?!0:!1,!0):a;if(!P(a))throw new TypeError("Array required");var g=e[4];f=e[2]?+e[2]:0;e=e[3]?+e[3]:a.length;e=-1===e?a.length:e+1;if(b)for(b=f;b<e;b++)Xa(a,b+g,c,!1,!0,!1,d);else if(a=a.slice(f,e),g)return"."===g.charAt(0)&&(g=g.slice(1)),a.map(function(h){return Xa(h,g)});return a}}function ic(a,b){if(J(a,b))return b}function V(a,b){return!!a&&"object"===(b||typeof a)}function Ea(a,b){b=b||typeof a;return null==a||"string"===b||"number"===
b||"boolean"===b}function Ib(a,b){var c;if(c=V(a)&&Hb(a,"Object",b))c="constructor"in a,c=!c&&!("toString"in a)||c&&!J(a,"constructor")&&J(a.constructor.prototype,"isPrototypeOf");if(c)a:{c=Object.prototype;for(var d in a){var e=a[d];if(!J(a,d)&&e!==c[d]){c=!1;break a}}c=!0}return c}function Kb(a,b){for(var c=0;c<a;c++)b(c)}function oa(a,b){B(b,function(c,d){a[d]=c});return a}function Ya(a){Ea(a)&&(a=Object(a));if(Te&&F(a))for(var b=a,c=0,d;d=b.charAt(c);)b[c++]=d;return a}function Pa(a,b,c){if(a===
b)return 0!==a||1/a===1/b;var d=ka(a);var e=ka(b);return d!==e?!1:Lb(a,d)&&Lb(b,e)?Ue(a,b,d,c):Mb(a,d)&&Mb(b,e)?a.size===b.size&&Pa(cd(a),cd(b),c):Nb(a,d)&&Nb(b,e)?a.size===b.size&&Pa(dd(a),dd(b),c):Ob(a,d)&&Ob(b,e)?a.toString()===b.toString():!1}function Ue(a,b,c,d){if(typeof a!==typeof b)return!1;if(V(a.valueOf())){if(a.length!==b.length)return!1;var e=0;var f=!0;ed(a,!1,d,function(g,h,k,l){k||g in b&&Pa(h,b[g],l)||(f=!1);e++;return f});if(!f||e!==Object.keys(b).length)return!1}return a.valueOf().toString()===
b.valueOf().toString()}function Za(a,b,c){var d=typeof a,e;if(Ea(a,d)&&(null==a||a===a))return d+a;var f=ka(a);if(Lb(a,f))V(a)?e=Ve(a,b,c)+a.toString():-Infinity===1/a?e="-0":a.valueOf&&(e=a.valueOf());else return c=jc(b,a),-1===c&&(c=b.length,b.push(a)),c;return d+f+e}function Ve(a,b,c){var d="";ed(a,!0,c,function(e,f,g,h){d+=g?"CYC":e+Za(f,b,h)});return d}function ed(a,b,c,d){function e(g,h){var k=!1;if(1<c.length)for(var l=c.length;l--;)c[l]===g&&(k=!0);c.push(g);d(h,g,k,c);c.pop()}function f(){for(var g=
Object.keys(a).sort(),h,k=0;k<g.length;k++)h=g[k],e(a[h],g[k])}c||(c=[]);b?f():B(a,e)}function Pb(a){return a>>>0==a&&4294967295!=a}function fd(a,b,c,d){var e=[],f;for(f in a)Pb(f)&&(c||(d?f<=b:f>=b))&&e.push(+f);e.sort(function(g,h){var k=g>b;return k!==h>b?k?-1:1:g-h});return e}function gd(a,b,c,d){var e=a.length;if(!P(b))return hd(a,b,e,c,d);var f=Array(b.length);D(b,function(g,h){f[h]=hd(a,g,e,c,d)});return f}function kc(a,b,c){a&&c&&(a%=b);0>a&&(a=b+a);return a}function hd(a,b,c,d,e){b=kc(b,
c,d);return e?a.charAt(b):a[b]}function Fa(a,b,c,d){return b?b.apply?b.apply(c,d||[]):P(b)?b.map(function(e){return Fa(a,e,c,d)}):U(a[b])?a[b].call(a):Jb(a,b):a}function ua(a){return a.split(" ")}function D(a,b){for(var c=0,d=a.length;c<d;c++){if(!(c in a)){d=a;for(var e=b,f=fd(d,c,void 0),g=0,h=f.length;g<h;g++)c=f[g],e.call(d,d[c],c,d);return d}b(a[c],c)}}function lc(a,b){for(var c=[],d=0,e=a.length;d<e;d++){var f=a[d];d in a&&b(f,d)&&c.push(f)}return c}function Ga(a,b){for(var c=[],d=0,e=a.length;d<
e;d++)d in a&&c.push(b(a[d],d));return c}function jc(a,b){for(var c=0,d=a.length;c<d;c++)if(c in a&&a[c]===b)return c;return-1}function nb(a,b,c){var d=Qb(10,pa(b||0));c=c||ob;0>b&&(d=1/d);return c(a*d)/d}function fa(a,b,c,d,e){d=pa(a).toString(d||10);d=Rb(e||"0",b-d.replace(/\.\d+/,"").length)+d;if(c||0>a)d=(0>a?"-":"+")+d;return d}function id(a){if(11<=a&&13>=a)return"th";switch(a%10){case 1:return"st";case 2:return"nd";case 3:return"rd";default:return"th"}}function mc(a,b){var c;var d=a.replace(jd,
function(e){e=A(Qa,e);"."===e&&(c=!0);return e});return c?parseFloat(d):parseInt(d,b||10)}function Rb(a,b){var c="";for(a=a.toString();0<b;)if(b&1&&(c+=a),b>>=1)a+=a;return c}function $a(a){return a.charAt(0).toUpperCase()+a.slice(1)}function kd(a,b,c){function d(m,n){var p=n[2],q=n[3],t=n[5];if(n[4]&&b){var x=t;var v=b}else if(p)x=p,v=a;else var u=q&&b?q:n[1]||n[0];if(v){g(c,p,t);var r=function(y,z){return v(y,x,z)}}m.push(r||f(u))}function e(m,n,p,q){if(q>p){var t=n.slice(p,q);h(t,"{");h(t,"}");
m.push(function(){return t})}}function f(m){return function(){return m}}function g(m,n,p){if(m&&!m(n,p))throw new TypeError("Invalid token "+(n||p)+" in format string");}function h(m,n){if(-1!==m.indexOf(n))throw new TypeError("Unmatched "+n+" in format string");}var k=We,l=Xe(function(m){var n=[],p=0,q;for(k.lastIndex=0;q=k.exec(m);)e(n,m,p,q.index),d(n,q),p=k.lastIndex;e(n,m,p,m.length);return n});return function(m,n,p){m=l(m);for(var q="",t=0;t<m.length;t++)q+=m[t](n,p);return q}}function ld(a){return N.human&&
N.human.L(a)||a}function ab(a,b){function c(e,f){if(e||-1<b.indexOf(f))d+=f}var d="";b=b||"";c(a.global,"g");c(a.ignoreCase,"i");c(a.multiline,"m");c(a.sticky,"y");return d}function bb(a){F(a)||(a=String(a));return a.replace(/([\\\/'*+?|()\[\]{}.^$-])/g,"\\$1")}function aa(a,b){return a["get"+(ba(a)?"UTC":"")+b]()}function cb(a,b,c,d){if(!d||c!==aa(a,b,c))a["set"+(ba(a)?"UTC":"")+b](c)}function Xe(a){var b={},c=0;return function(d){if(J(b,d))return b[d];c===Ye&&(b={},c=0);c++;return b[d]=a(d)}}function cd(a){var b=
Array(a.size),c=0;a.forEach(function(d){b[c++]=d});return b}function dd(a){var b=Array(a.size),c=0;a.forEach(function(d,e){b[c++]=[e,d]});return b}function Ze(){function a(c,d){for(var e=0;e<b.length;e++)d.push(c+b[e])}var b="FullYear Month Date Hours Minutes Seconds Milliseconds".split(" ");B({Function:"apply,call",RegExp:"compile,exec,test",Number:"toExponential,toFixed,toLocaleString,toPrecision",Object:"hasOwnProperty,isPrototypeOf,propertyIsEnumerable,toLocaleString",Array:"concat,join,pop,push,reverse,shift,slice,sort,splice,toLocaleString,unshift",
Date:"getTime,getTimezoneOffset,setTime,toDateString,toGMTString,toLocaleDateString,toLocaleString,toLocaleTimeString,toTimeString,toUTCString",String:"anchor,big,blink,bold,charAt,charCodeAt,concat,fixed,fontcolor,fontsize,indexOf,italics,lastIndexOf,link,localeCompare,match,replace,search,slice,small,split,strike,sub,substr,substring,sup,toLocaleLowerCase,toLocaleUpperCase,toLowerCase,toUpperCase"},function(c,d){var e=c.split(",");"Date"===d&&(a("get",e),a("set",e),a("getUTC",e),a("setUTC",e));
e.push("toString");Fb(d,e)})}function md(a,b,c,d){var e=a.length;var f=d?-1:1;var g=d?e-1:0;(c=Z(c))||0===c||(c=g);0>c&&(c=e+c);if(!d&&0>c||d&&c>=e)c=g;for(g=c;d&&0<=g||!d&&g<e;){if(!(g in a))return $e(a,b,c,d);if(Pb(g)&&a[g]===b)return g;g+=f}return-1}function $e(a,b,c,d){c=fd(a,c,!1,d);var e;for(c.sort(function(f,g){return d?g-f:f-g});void 0!==(e=c.shift());)if(a[e]===b)return+e;return-1}function nd(a,b,c,d){var e=a.length,f=0,g=w(c);la(b);if(0!=e||g)g||(c=a[d?e-1:f],f++);else throw new TypeError("Reduce called on empty array with no initial value");
for(;f<e;)g=d?e-f-1:f,g in a&&(c=b(c,a[g],g,a)),f++;return c}function nc(a){if(null==a)throw new TypeError("String required.");return String(a)}function oc(a){if(xa(a))throw new TypeError;return String(a)}function Ra(){return af("newDateInternal")()}function Ha(a){var b=new Date(a.getTime());ba(b,!!ba(a));return b}function od(a){if(isNaN(a.getTime()))throw new TypeError("Date is not valid");}function S(a){return aa(a,"Day")}function qa(a){return aa(a,"Date")}function ma(a){return aa(a,"Month")}function ya(a){return aa(a,
"FullYear")}function za(a,b){cb(a,"Date",b)}function pd(a){return 32-aa(new Date(ya(a),ma(a),32),"Date")}function Ia(a,b,c){if(R(b)){var d=S(a);if(c){c=0<c?1:-1;var e=b%7-d;e&&e/pa(e)!==c&&(b+=7*c)}za(a,qa(a)+b-d);return a.getTime()}}function pc(a,b){var c=ba(a)?0:a.getTimezoneOffset();var d=!0===b?":":"";if(!c&&b)return"Z";var e=fa(Z(-c/60),2,!0);c=fa(pa(c%60),2);return e+d+c}function qd(a,b){var c=a[0],d=a[1];if(b&&F(c)){var e={};if(c=c.match(/^(-?\d*[\d.]\d*)?\s?(\w+?)s?$/i)){if(E(f)){var f=+c[1];
isNaN(f)&&(f=1)}e[c[2].toLowerCase()]=f}c=e}else R(c)&&R(d)?(c=bf(a),d=null):V(c)&&(c=oa({},c));return[c,d]}function bf(a){var b={},c=0;rd(7,function(d){var e=a[c++];w(e)&&(b[d.name]=e)});return b}function qc(a,b,c){c=c||0;for(E(b)&&(b=7);b>=c&&!1!==a(Aa[b],b);b--);}function rd(a,b){for(;0<=a&&!1!==b(Aa[a],a);)a=pb(a)}function pb(a){return 6===a?4:5===a?3:a-1}function Sb(a,b,c,d){qc(function(e,f){var g=e.name;var h=A(a,rc(a,g));w(h)&&b(g,h,e,f);g=void 0;!1!==g&&4===f&&(g=A(a,rc(a,"weekday")),w(g)&&
b("weekday",g,e,f),g=void 0);return g},c,d)}function cf(a,b){Sb(a,b,7,4)}function Sa(a,b,c,d){var e={};e[b]=c;return Ja(a,e,d,1)}function sd(a,b,c){b=qd(b,!0);return Ja(a,b[0],b[1],c)}function qb(a,b){Ia(a,7*db((S(a)-b)/7)+b);return a}function td(a,b){var c=b-1;Ia(a,7*Ba((S(a)-c)/7)+c);return a}function rb(a,b,c){5===b&&qb(a,M.get(c).s());return na(a,pb(b))}function Tb(a,b,c,d){5===b&&td(a,M.get(c).s());return na(a,pb(b),d,!0)}function na(a,b,c,d){rd(b,function(e,f){var g=d?e.end:e.start;U(g)&&(g=
g(a));cb(a,e.method,g);return!w(c)||f>c});return a}function rc(a,b){return ic(a,b)||ic(a,b+"s")||"day"===b&&ic(a,"date")}function df(a){var b={},c;b[a]=1;Sb(b,function(d,e,f,g){c=g;return!1});return c}function Ub(a,b,c){var d=b>a;if(!d){var e=b;b=a;a=e}e=b-a;1<c.f&&(e=Z(e/c.f));if(c.m)for(a=Ha(a),e&&Sa(a,c.name,e);a<b;){Sa(a,c.name,1);if(a>b)break;e+=1}return d?-e:e}function ud(a,b){if(R(b)){var c=Ha(a),d=S(a);na(c,6);za(c,4);qb(c,1);za(c,qa(c)+7*(b-1));var e=ya(c);cb(a,"FullYear",e);e=ma(c);cb(a,
"Month",e);za(a,qa(c));Ia(a,d||7)}return a.getTime()}function eb(a,b,c,d){var e,f=0;E(c)&&(c=1);E(d)&&(d=4);var g=e=td(Ha(a),c),h=c,k=d;na(g,6);za(g,k);qb(g,h);b&&a<e&&(b=e=qb(Ha(a),c),na(b,6),za(b,d),qb(b,c));for(;e<=a;)za(e,qa(e)+7),f++;return f}function vd(a,b,c){var d=ya(a);var e=ma(a);if(0===e||11===e){if(!c){c=M.get(b);var f=c.s(b);var g=c.G(b)}a=eb(a,!1,f,g);0===e&&0===a?--d:11===e&&1===a&&(d+=1)}return d}function wd(a,b,c,d){var e;od(a);U(c)?d=c:e=c;c=ef(a,b);if(d&&(d=d.apply(a,c.concat(M.get(e)))))return xd(a,
d,e);0===c[1]&&(c[1]=1,c[0]=1);a=b?"duration":0<c[2]?"future":"past";return M.get(e).T(c,a)}function yd(a,b){var c=0,d=0;qc(function(e,f){d=pa(b(e));if(1<=d)return c=f,!1});return[d,c,a]}function ff(a){return yd(a,function(b){return Z(nb(a/b.f,1))})}function ef(a,b){b||(b=Ra(),a>b&&(b=new Date(b.getTime()-10)));return yd(a-b,function(c){return pa(Ub(a,b,c))})}function xd(a,b,c){od(a);b=zd[b]||b||"{long}";return Vb(b,a,c)}function sc(a,b){var c=aa(a,"Hours");return M.get(b).ampm[Z(c/12)]||""}function Ad(a,
b,c){var d;if(!isNaN(a.getTime())){if(F(b))switch(b=b.trim().toLowerCase(),!0){case "future"===b:return a.getTime()>Ra().getTime();case "past"===b:return a.getTime()<Ra().getTime();case "today"===b:return tc(a);case "tomorrow"===b:return tc(a,1);case "yesterday"===b:return tc(a,-1);case "weekday"===b:return 0<S(a)&&6>S(a);case "weekend"===b:return 0===S(a)||6===S(a);case w(d=Ta.weekdayMap[b]):return S(a)===d;case w(d=Ta.monthMap[b]):return ma(a)===d}return Bd(a,b,c)}}function Bd(a,b,c,d,e){var f=
0,g=0;ba(a)&&(e=e||{},e.fromUTC=!0,e.setUTC=!0);b=sb(null,b,e,!0);if(0<c){f=g=c;var h=!0}if(isNaN(b.date.getTime()))return!1;if(b.set&&b.set.specificity){if(w(b.set.edge)||w(b.set.shift)){var k=!0;rb(b.date,b.set.specificity,d)}if(k||6===b.set.specificity)var l=Tb(Ha(b.date),b.set.specificity,d).getTime();else l=Aa[b.set.specificity],l=Sa(Ha(b.date),l.name,1).getTime()-1;!h&&w(b.set.sign)&&b.set.specificity&&(f=50,g=-50)}c=a.getTime();h=b.date.getTime();l=l||h;if(a=b.set&&b.set.specificity?0:6E4*
(b.date.getTimezoneOffset()-a.getTimezoneOffset()))h-=a,l-=a;return c>=h-f&&c<=l+g}function tc(a,b){var c=Ra();b&&za(c,qa(c)+b);return ya(a)===ya(c)&&ma(a)===ma(c)&&qa(a)===qa(c)}function Ca(a,b,c){return sb(null,a,b,c).date}function sb(a,b,c,d){function e(y,z){var G=A(v,"params")||{};D(z.to,function(O,Ka){var K=y[Ka+1];if(K){if("yy"===O||"y"===O){O="year";var W=A(v,"prefer");K=+K;K+=50>K?2E3:1900;if(W){var ha=K-ya(u);ha/pa(ha)!==W&&(K+=100*W)}}else(W=A(uc,O))?(O=W.h||O,ha=W.C?W.C:W.sign?"+"===K?
1:-1:W.$?!!ha:+K.replace(/,/,"."),"month"===W.h&&--ha,K=ha):K=p.U(O,K);G[O]=K}});return G}function f(y,z){ba(y)&&!w(A(v,"fromUTC"))&&(v.fromUTC=!0);ba(y)&&!w(A(v,"setUTC"))&&(v.setUTC=!0);z&&(y=new Date(y.getTime()));return y}function g(){D(x,function(y){y.call()})}function h(y){y=y.toLowerCase();p=M.get(A(v,"locale"));for(var z=0,G,O;G=p.compiledFormats[z];z++)if(O=y.match(G.reg)){p.M(G,z);r=e(O,G);if(w(r.timestamp)){y=r.timestamp;r=null;break}w(r.ampm)&&(z=r.ampm,1===z&&12>r.hour?r.hour+=12:0===
z&&12===r.hour&&(r.hour=0));if(r.utc||w(r.tzHour))if(z=r.tzHour,G=r.tzMinute,O=r.tzSign,ba(u,!0),z=(O||1)*(60*(z||0)+(G||0)))r.minute=(r.minute||0)-z;w(r.shift)&&E(r.unit)&&(w(r.month)?r.unit=7:w(r.weekday)&&(r.unit=5));w(r.num)&&E(r.unit)&&(z=r.num,w(r.weekday)?m(z):w(r.month)&&(r.date=r.num));r.midday&&k(r.midday);w(r.day)&&(na(u,3),E(r.unit)&&(r.unit=4,r.num=r.day,delete r.day));w(r.unit)&&(z=r.unit,G=w(r.num)?r.num:1,w(r.weekday)&&(6===z?(m(G),G=1):(Ja(u,{weekday:r.weekday},!0),delete r.weekday)),
r.half&&(G*=r.half),w(r.shift)?G*=r.shift:r.sign&&(G*=r.sign),w(r.day)&&(G+=r.day,delete r.day),n(z),r[Ta.units[z]]=G,q=!0);r.edge&&l(r.edge,r);r.yearSign&&(r.year*=r.yearSign);break}r?q?Ja(u,r,!1,1):(ba(u)&&na(u,3),Ja(u,r,!0,0,A(v,"prefer"),t)):(u=new Date(y),A(v,"fromUTC")&&u.setTime(u.getTime()+6E4*u.getTimezoneOffset()));g();return u}function k(y){r.hour=y%24;23<y&&x.push(function(){Sa(u,"date",Z(y/24))})}function l(y,z){var G=z.unit;G||cf(z,function(Ka,K,W,ha){"weekday"===Ka&&w(z.month)||(G=
ha)});if(6===G&&w(z.weekday)){var O=z.weekday;delete z.weekday}x.push(function(){if(0>y)rb(u,G,A(v,"locale"));else if(0<y){if(1===y){var Ka=4;rb(u,4)}Tb(u,G,A(v,"locale"),Ka)}w(O)&&(Ia(u,O,-y),na(u,3))});z.specificity=6===G?4:G-1}function m(y){r.weekday=7*(y-1)+r.weekday;t=r.date=1}function n(y){var z;Sb(r,function(G,O,Ka,K){if(K>=y)return u.setTime(NaN),!1;K<y&&(z=z||{},z[G]=O,delete r[rc(r,G)])});z&&(x.push(function(){Ja(u,z,!0,!1,A(v,"prefer"),t)}),r.edge&&(l(r.edge,z),delete r.edge))}var p,q,
t;var x=[];var v=function(y){y=F(y)?{locale:y}:y||{};y.prefer=+!!A(y,"future")-+!!A(y,"past");return y}(c);var u=a&&b?f(a,!0):Ra();ba(u,A(v,"fromUTC"));if(F(b))u=h(b);else if(ia(b))u=f(b,J(v,"clone")||d);else if(V(b)){var r=oa({},b);Ja(u,r,!0)}else(R(b)||null===b)&&u.setTime(b);ba(u,!!A(v,"setUTC"));return{set:r,date:u}}function Ja(a,b,c,d,e,f){function g(){var l=Aa[k];d=e;h(l.name,1,l,k)}function h(l,m,n,p){var q=n.method,t;e&&!k&&(k="weekday"===l?5:4===p?6:p+1);p>b.specificity||(b.specificity=p);
if(t=m%1){if(p){var x=Aa[pb(p)];t=ob(n.f/x.f*t);b[x.name]=t}m=Z(m)}if("weekday"===l)d||Ia(a,m,f);else if(l=6===p&&28<qa(a),d&&!n.m)a.setTime(a.getTime()+m*d*n.f);else{d&&(5===p&&(m*=7,q=Aa[4].method),m=m*d+aa(a,q));n=q;p=m;q=d;"ISOWeek"===n?ud(a,p):cb(a,n,p,q);if(n=l)0>m&&(m=m%12+12),n=m%12!==ma(a);n&&za(a,0)}}var k;if(R(b)&&d)b={millisecond:b};else if(R(b))return a.setTime(b),a;Sb(b,h);c&&b.specificity&&na(a,pb(b.specificity));a:{if(k&&!(7<k))switch(e){case -1:c=a>Ra();break a;case 1:c=a<Ra();break a}c=
void 0}c&&g();return a}function Wb(a){var b=a.join("");return a&&a.length?b.length===a.length?"["+b+"]":Ga(a,bb).join("|"):""}function ra(a,b){1<a.length&&(a="(?:"+a+")");b&&(a+="?");return a}function gf(a,b,c){a=Cd[a];return b=a.A?ra(b+ra(c)):a.J?b+ra(a.J+"|"+c):b+ra(c,!0)}function Dd(a,b,c,d){var e;1<c&&(e=a[b+(c-1)*d]);return e||a[b]}function Ed(a){function b(c){this.W(c)}b.prototype={H:function(c,d){return this.monthSuffix?c+1+this.monthSuffix:Dd(this.months,c,d,12)},I:function(c,d){return Dd(this.weekdays,
c,d,7)},U:function(c,d){var e=this[c+"Map"],f;e&&(f=e[d]);E(f)&&(f=this.P(d),"month"===c&&--f);return f},P:function(c){var d=this.numeralMap[c];if(w(d))return d;d=+c.replace(/,/,".");if(!isNaN(d))return d;d=this.R(c);isNaN(d)||(this.numeralMap[c]=d);return d},R:function(c){var d=1,e=0,f;var g=c.split("");for(var h=g.length-1;f=g[h];h--){c=A(this.numeralMap,f);E(c)&&(c=A(Qa,f)||0);(f=0<c&&0===c%10)?(k&&(e+=d),h?d=c:e+=c):(e+=c*d,d*=10);var k=f}return e},S:function(c){return this.ordinalSuffix||id(c)},
T:function(c,d){return this.F(c,d)},O:function(c){return this.F(ff(Q(0,c)),"duration")},s:function(){var c=this.firstDayOfWeek;return w(c)?c:1},G:function(){return this.firstDayOfWeekYear||4},F:function(c,d){var e=c[0],f=c[1],g=c[2],h=this[d]||this.relative;if(U(h))return h.call(this,e,f,g,d);var k=this.units[8*(this.plural&&1!==e?1:0)+f]||this.units[f];var l=this[0<g?"fromNow":"ago"];return h.replace(/\{(.*?)\}/g,function(m,n){switch(n){case "num":return e;case "unit":return k;case "sign":return l}})},
M:function(c,d){this.compiledFormats.splice(d,1);this.compiledFormats.unshift(c)},addFormat:function(c,d){function e(h){var k,l=h.match(/\?$/),m=h.match(/^(\d+)\??$/),n=h.match(/(\d)(?:-(\d))?/),p=h.replace(/[^a-z]+$/i,"");if(k=A(g.parsingAliases,p))return h=f(k),l&&(h=ra(h,!0)),h;if(m)h=g.tokens[m[1]];else if(k=A(uc,p))h=k.src;else if(k=A(g.parsingTokens,p)||A(g,p),p=p.replace(/s$/,""),k||(k=A(g.parsingTokens,p)||A(g,p+"s")),F(k)){h=k;var q=g[p+"Suffix"]}else n&&(k=lc(k,function(t,x){var v=x%(g.units?
8:k.length);return v>=n[1]&&v<=(n[2]||n[1])})),h=Wb(k);if(!h)return"";m?h=ra(h):(d.push(p),h="("+h+")");q&&(h=gf(p,h,q));l&&(h+="?");return h}function f(h){h=h.replace(/ /g," ?");return h.replace(/\{([^,]+?)\}/g,function(k,l){var m=l.split("|");return 1<m.length?ra(Ga(m,e).join("|")):e(l)})}var g=this;d||(d=[],c=f(c));g.addRawFormat(c,d)},addRawFormat:function(c,d){this.compiledFormats.unshift({reg:RegExp("^ *"+c+" *$","i"),to:d})},W:function(c){function d(l,m,n,p){var q=l,t=[];k[q]||(q+="s");if(!n){n=
{};var x=!0}e(q,function(v,u,r){u=u*m+r;r=p?p(r):r;n[v]=r;n[v.toLowerCase()]=r;t[u]=v});k[q]=t;x&&(k[l+"Map"]=n)}function e(l,m){D(k[l],function(n,p){f(n,function(q,t){m(q,t,p)})})}function f(l,m){var n=Ga(l.split("+"),function(p){return p.replace(/(.+):(.+)$/,function(q,t,x){return Ga(x.split("|"),function(v){return t+v}).join("|")})}).join("|");D(n.split("|"),m)}function g(l,m,n){D(k[l],function(p){m&&(p=h(p,n));k.addFormat(p)})}function h(l,m){if(m)var n=ra("{time}[,\\s\\u3000]",!0)+l;else{n=",?[\\s\\u3000]";
var p;(p=Wb(k.timeMarkers))&&(n+="| (?:"+p+") ");n=ra(n,k.timeMarkerOptional);n=ra(n+"{time}",!0);n=l+n}return n}var k=this;k.compiledFormats=[];k.parsingAliases={};k.parsingTokens={};oa(k,c);(function(){D(hf,function(l){var m=k[l];F(m)?k[l]=m.split(","):m||(k[l]=[])})})();d("month",12);d("weekday",7);d("unit",8);d("ampm",2);(function(){var l={};d("numeral",10,l);d("article",1,l,function(){return 1});d("placeholder",4,l,function(m){return Qb(10,m+1)});k.numeralMap=l})();k.parsingAliases.time=k.ampmFront?
"{ampm?} {hour} (?:{minute} (?::?{second})?)?":k.ampm.length?"{hour}(?:[.:]{minute}(?:[.:]{second})? {ampm?}| {ampm})":"{hour}(?:[.:]{minute}(?:[.:]{second})?)";k.parsingAliases.tzOffset="(?:{Z}|{GMT?}(?:{tzSign}{tzHour}(?::?{tzMinute}(?: \\([\\w\\s]+\\))?)?)?)?";(function(){B(Cd,function(l,m){var n=l.i?uc[l.i].src:l.src;if(l.Y||k.numeralUnits){var p="";var q=k.numerals.concat(k.placeholders).concat(k.articles);k.allowsFullWidth&&(q=q.concat(Fd.split("")));q.length&&(p="|(?:"+Wb(q)+")+");n+=p}(q=
k[m+"s"])&&q.length&&(n+="|"+Wb(q));k.parsingTokens[m]=n})})();(function(){qc(function(l,m){var n=k.timeSuffixes[m];n&&(k[(l.alias||l.name)+"Suffix"]=n)})})();(function(){D(k.modifiers,function(l){var m=l.name,n=m+"Map";var p=k[n]||{};f(l.src,function(q,t){var x=A(k.parsingTokens,m),v=l.value;p[q]=v;k.parsingTokens[m]=x?x+"|"+q:q;"sign"===l.name&&0===t&&(k[1===v?"fromNow":"ago"]=q)});k[n]=p})})();(function(){D(jf,function(l){var m=l.src;l.mdy&&k.mdy&&(m=l.mdy);l.time?(k.addFormat(h(m,!0)),k.addFormat(h(m))):
k.addFormat(m)});k.addFormat("{time}")})();g("parse");g("timeParse",!0);g("timeFrontParse",!0,!0)}};return new b(a)}function Xb(a,b){return Rb(w(b)?b:" ",a)}function Gd(a,b,c,d,e){if(a.length<=b)return a.toString();d=E(d)?"...":d;switch(c){case "left":return a=e?tb(a,b,!0):a.slice(a.length-b),d+a;case "middle":c=Ba(b/2);var f=db(b/2);b=e?tb(a,c):a.slice(0,c);a=e?tb(a,f,!0):a.slice(a.length-f);return b+d+a;default:return b=e?tb(a,b):a.slice(0,b),b+d}}function ub(a,b,c){var d,e=[];if(U(b)){c=b;var f=
/[\s\S]/g}else b?F(b)?f=RegExp(bb(b),"gi"):xa(b)&&(f=RegExp(b.source,ab(b,"g"))):f=/[\s\S]/g;b=[];for(var g;null!=(d=f.exec(a));)f.lastIndex===g?f.lastIndex+=1:b.push(d[0]),g=f.lastIndex;if(b)for(g=0,f=b.length;g<f;g++)if(d=b[g],e[g]=d,c)if(d=c.call(a,d,g,b),!1===d)break;else w(d)&&(e[g]=d);return e}function kf(a,b){return ub(a.trim(),/\S+/g,b)}function Hd(a,b){var c=Array(a.length),d;var e=0;for(d=a.length;e<d;e++){var f=a.charCodeAt(e);c[e]=f;b&&b.call(a,f,e,a)}return c}function vb(a){var b=N.acronyms&&
N.acronyms.reg;return a.replace(/[-\s]+/g,"_").replace(b,function(c,d){return(0<d?"_":"")+c.toLowerCase()}).replace(/([A-Z\d]+)([A-Z][a-z])/g,"$1_$2").replace(/([a-z\d])([A-Z])/g,"$1_$2").toLowerCase()}function lf(a,b){a=vb(a);return a.replace(mf,function(c,d,e,f){c=!1!==b||0<f;return(d=N.acronyms&&N.acronyms.find(e))&&c?d:c?vc(e,!0):e})}function vc(a,b,c){b&&(a=a.toLowerCase());return c?a.replace(nf,$a):$a(a)}function of(a){var b=/[.:;!]$/,c;a=ld(a);a=vb(a).replace(/_/g," ");return kf(a,function(d,
e,f){d=N.human&&N.human.find(d)||d;d=N.acronyms&&N.acronyms.find(d)||d;var g=0==e;f=e==f.length-1;e=b.test(d);g=g||f||e||c;c=e;return g||-1===jc(pf,d)?vc(d,!1,!0):d}).join(" ")}function tb(a,b,c){if(c)return tb(a.split("").reverse().join(""),b).split("").reverse().join("");var d=0;return lc(a.split(qf),function(e){d+=e.length;return d<=b}).join("")}function rf(a){return a.replace(sf,function(b,c,d){return Id[d]||X(c?parseInt(d,16):+d)})}function Jd(a,b,c){var d=0;F(b)?b=RegExp(bb(b),"g"):b&&!b.global&&
(b=RegExp(b.source,ab(b,"g")));if(c){var e=c;c=function(){var f=e[d++];return null!=f?f:""}}else c="";return a.replace(b,c)}function Kd(a,b,c,d){b=F(b)?[b]:b;b=Ga(b||[],function(e){return bb(e)}).join("|");b=b.replace("all","")||"[^\\s>]+";return Ld(a.toString(),RegExp("<(\\/)?("+b+")(\\s+[^<>]*?)?\\s*(\\/)?>","gi"),d,c)}function Ld(a,b,c,d,e){function f(y,z,G,O,Ka){var K=a.slice(k,y),W="",ha="";F(d)?ha=d:d&&(ha=d.call(e,z,K,G,e)||"");c?W=ha:K=ha;K&&(K=Ld(K,b,c,d,e));h+=W+K+(Ka?"":W);k=y+(O||0)}var g,
h="",k=0,l=0;e=e||a;for(b=RegExp(b.source,"gi");g=b.exec(a);){var m=g[2],n=(g[3]||"").slice(1),p=!!g[1],q=!!g[4],t=g[0].length,x=-1!==jc(tf,m.toLowerCase());q=!p&&!q&&!x;var v=m===u;u||(h+=a.slice(k,g.index),k=g.index);if(q)if(u)v&&l++;else{var u=m;var r=n;l++;k+=t}else p&&v?(l--,0===l&&(f(g.index,u,r,t,x),r=u=null)):u||f(g.index,m,n,t,x)}u&&f(a.length,u,r);return h+=a.slice(k)}function Md(a,b,c){F(b)&&(b=a.indexOf(b),-1===b&&(b=c?a.length:0));return b}function Nd(a,b){var c;a&&a.constructor&&P(a.constructor.prototype)?
c=b?fb(a):a:V(a)||F(a)?c=Array.from(a):w(a)&&(c=[a]);return c||[]}function fb(a){var b=Array(a.length);D(a,function(c,d){b[d]=c});return b}function uf(a){var b=[];b.push(a);return b}function vf(a,b){var c=fb(a),d=c.length;var e=P(b)?b:[b];c.length+=e.length;D(e,function(f,g){c[d+g]=f});return c}function Od(a,b,c){c=+c;isNaN(c)&&(c=a.length);c=[c,0];w(b)&&(c=c.concat(b));a.splice.apply(a,c);return a}function Pd(a,b){var c=[],d={},e=[];D(a,function(f,g){var h=b?Fa(f,b,a,[f,g,a]):f;h=Za(h,e);J(d,h)||
(c.push(f),d[h]=!0)});return c}function Qd(a,b,c){var d=[];b=b||Infinity;c=c||0;D(a,function(e){P(e)&&c<b?d=d.concat(Qd(e,b,c+1)):d.push(e)});return d}function wf(a,b){return lc(a,function(c){return c||!b&&null!=c&&c.valueOf()===c.valueOf()})}function xf(a,b,c){var d={},e;D(a,function(f,g){e=Fa(f,b,a,[f,g,a]);J(d,e)||(d[e]=[]);d[e].push(f)});c&&B(d,c);return d}function Rd(a,b,c){var d=[],e={},f=[];P(b)||(b=uf(b));D(b,function(g){e[Za(g,f)]=!0});D(a,function(g){var h=Za(g,f);J(e,h)!==c&&(delete e[h],
d.push(g))});return d}function Sd(a,b){var c;if(F(a)&&F(b)){var d=gb("sortCollate");return d(a,b)}if(P(a)&&P(b)){if(a.length<b.length)return-1;if(a.length>b.length)return 1;for(c=0;c<a.length;c++)if(d=Sd(a[c],b[c]),0!==d)return d;return 0}return a<b?-1:a>b?1:0}function Td(a,b,c){F(a)||(a=String(a));c&&(a=a.toLowerCase());b&&(a=a.replace(b,""));return a}function Ud(a,b,c){a=a.charAt(b);return A(c,a)||a}function wc(a,b,c,d,e){if(P(a)){for(var f,g,h=[],k=0,l=a.length;k<l;k++)f=a[k],f=(g=d+(d&&b?"[]":
""))||V(f)?wc(f,b,c,g,e):xc(f),h.push(f);d=h.join("&")}else V(a)&&a.toString===fc?d=yf(a,b,c,d,e):d?(a=c?c(a,d):ia(a)?a.getTime():a,d=xc(d)+"="+xc(a)):d="";return d}function yf(a,b,c,d,e){var f=[];B(a,function(g,h){f.push(wc(g,b,c,d&&b?d+"["+h+"]":d?d+e+h:h,e))});return f.join("&")}function xc(a){return a||!1===a||0===a?encodeURIComponent(a):""}function zf(a,b){var c=String(a||"").replace(/^.*?\?/,""),d={},e;b=b||{};c&&D(c.split("&"),function(f){f=f.split("=");var g=decodeURIComponent(f[0]);f=2===
f.length?decodeURIComponent(f[1]):"";e=!1!==b.auto;var h=g,k=b.deep;g=e;var l=b.separator,m=b.transform,n;if(l){h=h.split(l);k=h[0];for(var p=1,q=h.length;p<q;p++)k+="["+h[p]+"]";h=k;k=!0}!0===k&&(n=h.match(Af))?Bf(d,n,f,k,g,l,m):Vd(d,h,f,g,m)});return d}function Bf(a,b,c,d,e,f,g){var h=b[1];b=b[2].slice(1,-1).split("][");D(b,function(k){J(a,h)||(a[h]=k?{}:[]);a=A(a,h);h=k?k:a.length.toString()});Vd(a,h,c,e,g)}function Vd(a,b,c,d,e){var f;e&&(f=e(c,b,a));w(f)?c=f:d&&(c=Cf(a,b,c));a[b]=c}function Cf(a,
b,c){if(c){if("true"===c)return!0;if("false"===c)return!1}else return null;var d=+c;if(!isNaN(d)&&""!==c&&!Df.test(c))return d;a=A(a,b);return c&&a?P(a)?a.concat(c):[a,c]:c}function yc(a,b,c){c=c||{};return Yb(a,b,c.deep,c.resolve,c.hidden,c.descriptor)}function zc(a,b,c){P(b)||(b=[b]);D(b,function(d){return yc(a,d,c)});return a}function Ef(a,b,c){Ac&&a?Wd(Ac,b,c,a):B(b,c);Xd&&Wd(Xd,b,c,a)}function Wd(a,b,c,d){a=a(b);for(var e,f=0,g;g=a[f];f++)e=Yd(b,g),(e.enumerable||d)&&c(b[g],g)}function Yb(a,
b,c,d,e,f){var g=U(d),h=!1!==d;E(a)?a=Zd(b):h&&ia(a)&&ia(b)&&a.setTime(b.getTime());if(Ea(a))return b;Ea(b)&&(b=Ya(b));Ef(e,b,function(k,l){var m=b[l];var n=A(a,l);if(g){var p=d(l,n,m,a,b);if(E(p))return;if(w(p)&&p!==C){m=p;var q=!0}}else if(E(m))return;if((q=!q&&c&&V(m)&&!xa(m))||h||!w(n))q&&(m=Yb(n,m,c,d,e,f)),Ac&&f?(n=a,q=Yd(b,l),w(q.value)&&(q.value=m),Gb(n,l,q)):a[l]=m});return a}function Zd(a){var b=ka(a);if(P(a,b))return[];if(Ib(a,b))return{};if(ia(a,b))return new Date(a.getTime());if(xa(a,
b))return RegExp(a.source,ab(a));if(Ea(a&&a.valueOf()))return a;throw new TypeError("Must be a basic data type");}function Bc(a,b){var c=Zd(a);return Yb(c,a,b,!0,!0,!0)}function Ff(a){var b=[];B(a,function(c){b.push(c)});return b}function Gf(a,b){var c=b;U(b)||(c=function(){if(b)a[b]()});c.call(a,a);return a}function $d(a,b,c){var d,e={};b=[].concat(b);B(a,function(f,g){d=!1;for(var h=0;h<b.length;h++){var k=b[h],l=g;(xa(k)?k.test(l):V(k)?l in k:l===String(k))&&(d=!0)}d===c&&(e[g]=f)});return e}function Hf(a,
b){var c=wa(b);B(a,function(d,e){c(d,e,a)&&delete a[e]});return a}function If(a,b){var c={},d=wa(b);B(a,function(e,f){d(e,f,a)||(c[f]=e)});return c}function ae(a,b,c){if(!V(a))return c?a:{};b=Ya(b);return Yb({},a,!1,function(d,e,f){if((d in b&&Pa(f,b[d]))!==c)return f})}function be(a,b){var c=0;wb(a,b,function(d){c+=d});return c}function ce(a,b){var c=0,d=0;wb(a,b,function(e){c+=e;d++});return c/(d||1)}function de(a,b){var c=[];wb(a,b,function(f){c.push(f)});var d=c.length;if(!d)return 0;c.sort(function(f,
g){return(f||0)-(g||0)});var e=Z(d/2);return d%2?c[e]:(c[e-1]+c[e])/2}function xb(a,b,c,d,e){var f=[],g,h;if(hb(b)){var k=b;b=c}wb(a,b,function(l,m){if(E(l))throw new TypeError("Cannot compare with undefined");g=e?m:a[m];if(l===h)f.push(g);else if(E(h)||d&&l>h||!d&&l<h)f=[g],h=l});return ee(f,a,k,e)}function Zb(a,b,c,d,e){var f={},g=[];if(hb(b)){var h=b;b=c}wb(a,b,function(l,m){var n=Za(l,g),p=A(f,n)||[];p.push(e?m:a[m]);f[n]=p});d=xb(f,!!h,"length",d,!0);if(h){var k=[];B(d,function(l){k=k.concat(l)})}else k=
A(f,d);return ee(k,a,h,e)}function ee(a,b,c,d){if(d&&c)return a.reduce(function(e,f){e[f]=b[f];return e},{});a&&!c&&(a=a[0]);return a}function wb(a,b,c){var d=P(a);B(a,function(e,f){if(d){if(!Pb(f))return;f=+f}var g=Fa(e,b,a,[e,f,a]);c(g,f)})}function fe(a,b){if(U(a))return a;if(a)return function(c,d,e){return Fa(c,a,b,[c,d,e])}}function La(a){if(U(a))return a;var b=wa(a);return function(c,d,e){return b(c,d,e)}}function ib(a,b){var c=Array.prototype[a];return function(d,e,f,g){var h=Array(2);ad(0<
g);h[0]=b(e,f);h[1]=f;return c.apply(d,h)}}function Jf(a,b){la(b);B(a,function(c,d){b(c,d,a)});return a}function Kf(a,b){var c={};B(a,function(d,e){c[e]=Fa(d,b,a,[d,e,a])});return c}function Lf(a,b,c){var d=w(c);B(a,function(e,f){d?c=b(c,e,f,a):(c=e,d=!0)});return c}function Mf(a,b){var c=wa(b),d={};B(a,function(e,f){c(e,f,a)&&(d[f]=e)});return d}function Nf(a,b){var c=wa(b),d=0;B(a,function(e,f){c(e,f,a)&&d++});return d}function Cc(a){var b=Array.prototype[a];return function(c,d){var e=wa(d);return b.call(Object.keys(c),
function(f){return e(c[f],f,c)})}}function Dc(a,b,c,d){var e=a.toFixed(20),f=e.search(/\./);e=e.search(/[1-9]/);f-=e;0<f&&--f;e=c.split(",");1===e.length&&(e=c.split(""));var g=e.indexOf("|");-1===g&&(g="_"===e[0]?0:e.length);var h=Q(sa(db(f/3),e.length-g-1),-g);for(c=e[h+g];"_"===c;)h+=0>h?-1:1,c=e[h+g];"|"===c&&(c="");-9>f&&(b=pa(f)-9);d=d?Qb(2,10*h):Qb(10,3*h);return ge(nb(a/d,b||0))+c}function ge(a,b){var c="";var d=he("decimal");var e=he("thousands");var f=R(b)?nb(a,b||0).toFixed(Q(b,0)):a.toString();
f=f.replace(/^-/,"");var g=f.split(".");var h=g[0];g=g[1];if(/e/.test(f))c=f;else for(f=h.length;0<f;f-=3)f<h.length&&(c=e+c),c=h.slice(Q(0,f-3),f)+c;g&&(c+=d+Rb("0",(b||0)-g.length)+g);return(0>a?"-":"")+c}function Ec(a){return function(b,c){return c?nb(b,c,a):a(b)}}function jb(a,b,c,d,e){b=Oa(b||0);$b(a)||$b(a,[]);Fc(a,!1);$b(a).push(setTimeout(function(){Fc(a)||c.apply(d,e||[])},b))}function ie(a){var b=$b(a),c;if(P(b))for(;c=b.shift();)clearTimeout(c);Fc(a,!0);return a}function je(a,b,c,d){function e(){if(f.length<
d-(g&&c?1:0)){for(var n=[],p=0,q=arguments.length;p<q;p++)n.push(arguments[p]);f.push([this,n])}g||(g=!0,c?m():jb(e,k,m));return h}var f=[],g=!1,h;b=b||1;d=d||Infinity;var k=Ba(b);var l=ob(k/b)||1;var m=function(){var n=f.length,p;if(0!=n){for(p=Q(n-l,0);n>p;)h=Function.prototype.apply.apply(a,f.shift()),n--;jb(e,k,function(){g=!1;m()})}};return e}function Of(){for(var a=arguments,b=a.length,c=Array(b);b--;)c[b]=a[b];return c}function Pf(a,b,c){var d={},e=[],f=0;return function(){var g=b.apply(this,
arguments);g=Za(g,e);if(J(d,g))return A(d,g);f===c&&(d={},e=[],f=0);f++;return d[g]=a.apply(this,arguments)}}function ea(a,b){this.start=Gc(a);this.end=Gc(b)}function ke(a){return F(a)?a.charCodeAt(0):a}function le(a){return null==a?a:ia(a)?a.getTime():a.valueOf()}function me(a){a=a.toString().split(".");return a[1]?a[1].length:0}function Qf(a,b){return Q(me(a),me(b))}function Gc(a){return ia(a)?new Date(a.getTime()):le(a)}function ne(a){var b=le(a);return(!!b||0===b)&&-Infinity!==a&&Infinity!==a}
function ac(a){return ne(a.start)&&ne(a.end)&&typeof a.start===typeof a.end}function bc(a,b,c,d){var e=a.start,f=a.end,g=f<e,h=e,k=0,l=[];if(!ac(a))return c?NaN:[];U(b)&&(d=b,b=null);b=b||1;if(R(e)){var m=Qf(e,b);var n=function(){return nb(h+b,m)}}else if(F(e))n=function(){return X(h.charCodeAt(0)+b)};else if(ia(e)){n=oe(b);b=n[0];var p=n[1];n=function(){return pe(h,b,p)}}for(g&&0<b&&(b*=-1);g?h>=f:h<=f;)c||l.push(h),d&&d(h,k,a),h=n(),k++;return c?k-1:l}function oe(a){if(R(a))return[a,"Milliseconds"];
var b=a.match(Rf);a=+b[1]||1;b=$a(b[2].toLowerCase());b.match(/hour|minute|second/i)?b+="s":"Year"===b?b="FullYear":"Week"===b?(b="Date",a*=7):"Day"===b&&(b="Date");return[a,b]}function pe(a,b,c){var d=qe[c];d?d=new Date(a.getTime()+b*d):(d=new Date(a),cb(d,c,aa(a,c)+b));return d}function Hc(a,b){var c=a.start,d=a.end,e=d<c?d:c;c=c>d?c:d;return Gc(b<e?e:b>c?c:b)}function kb(a){return ia(a)?a:null==a?new Date:Y.create?Y.create(a):new Date(a)}function I(a,b){b=b||a;yb("plural",a,b);F(a)&&H(b,a)}function H(a,
b){yb("singular",a,b)}function Da(a,b){var c=RegExp(a+"$","i"),d=RegExp(b+"$","i");I(c,b);I(d,b);H(d,a);H(c,a)}function Sf(a){D(ua(a),function(b){I(b)})}function re(a,b){yb("human",a,b)}function Tf(){var a=[];B(N.acronyms.map,function(b,c){c===b&&a.push(b)});a.sort(function(b,c){return c.length-b.length});N.acronyms.reg=RegExp("\\b"+a.join("|")+"\\b","g")}function yb(a,b,c){N[a]||(N[a]=new Ic);N[a].add(b,c)}function Jc(a,b,c,d){var e=cc[d];b=(b||"").replace(/all/,"").replace(/(\w)lphabet|umbers?|atakana|paces?|unctuation/g,
"$1");return a.replace(c,function(f){var g=e[f],h;if(g){if(""===b&&g.all)return g.all;for(var k=0,l=b.length;k<l;k++)if(h=g[b.charAt(k)])return h}return f})}var C,Va="undefined"!==typeof global&&global.Object===Object?global:this,Uf="undefined"!==typeof module&&module.exports,Tc=!1,Eb={},Uc={},Gb=Object.defineProperty&&Object.defineProperties?Object.defineProperty:Je,Wc=Sc("Chainable"),Xc=Object.getOwnPropertyNames,fc=Object.prototype.toString,Ke=Object.prototype.hasOwnProperty;(function(){C=Va.Sugar;
if(!C){C=function(a){B(C,function(b,c){J(Eb,c)&&b.extend(a)});return C};if(Uf)module.exports=C;else try{Va.Sugar=C}catch(a){}B("Object Number String Array Date RegExp Function".split(" "),function(a){Rc(a)});L(C,"extend",C);L(C,"toString",Ee);L(C,"createNamespace",Rc);L(C,"util",{hasOwn:J,getOwn:A,setProperty:L,classToString:ka,defineProperty:Gb,forEachProperty:B,mapNativeToChainable:Fb})}})();var Te=!("0"in Object("a")),Se=/^(.*?)\[([-\d]*)\.\.([-\d]*)\](.*)$/,We=/([{}])\1|\{([^}]*)\}|(%)%|(%(\w*))/g,
lb=C.Object,ca=C.Array,Y=C.Date,ja=C.String,ta=C.Number,Kc=C.Function,se=C.RegExp;J=C.util.hasOwn;A=C.util.getOwn;L=C.util.setProperty;ka=C.util.classToString;Gb=C.util.defineProperty;B=C.util.forEachProperty;Fb=C.util.mapNativeToChainable;var Lb,hb,R,F,ia,xa,U,P,Mb,Nb,Ob,te=Na("alias"),Ma=Na("defineStatic"),T=Na("defineInstance"),zb=Na("defineStaticPolyfill"),Ua=Na("defineInstancePolyfill"),gc=Na("defineInstanceAndStatic"),Ab=Na("defineInstanceWithArguments"),Z=Math.trunc||function(a){return 0!==
a&&isFinite(a)?0>a?Ba(a):db(a):a},jd,Qa,Fd,pa=Math.abs,Qb=Math.pow,sa=Math.min,Q=Math.max,Ba=Math.ceil,db=Math.floor,ob=Math.round,X=String.fromCharCode,N={},ba=mb("utc"),Ye=1E3;(function(){function a(g){f["[object "+g+"]"]=!0}function b(g,h){return h&&Hb(new h,"Object")?c(h):d(g)}function c(g){var h=String(g);return function(k){return String(k.constructor)===h}}function d(g){return function(h,k){return Hb(h,g,k)}}function e(g){var h=g.toLowerCase();return function(k){var l=typeof k;return l===h||
"object"===l&&Hb(k,g)}}var f={};(function(){var g=ua("Boolean Number String Date RegExp Function Array Error Set Map");hb=e(g[0]);R=e(g[1]);F=e(g[2]);ia=b(g[3]);xa=b(g[4]);U=b(g[5]);P=Array.isArray||b(g[6]);Ob=b(g[7]);Mb=b(g[8],"undefined"!==typeof Set&&Set);Nb=b(g[9],"undefined"!==typeof Map&&Map);a("Arguments");a(g[0]);a(g[1]);a(g[2]);a(g[3]);a(g[4]);a(g[6])})();(function(){D(ua("Int8 Uint8 Uint8Clamped Int16 Uint16 Int32 Uint32 Float32 Float64"),function(g){a(g+"Array")})})();Lb=function(g,h){h=
h||ka(g);return f[h]||Ib(g,h)}})();(function(){var a="";Qa={};for(var b=0,c;9>=b;b++)c=X(b+65296),a+=c,Qa[c]=X(b+48);Qa[","]="";Qa["\uff0e"]=".";Qa["."]=".";jd=RegExp("["+(a+"\uff0e,.]"),"g");Fd=a})();var Vf="valueOf toString constructor isPrototypeOf hasOwnProperty toLocaleString propertyIsEnumerable".split(" ");(function(){if(!{toString:1}.propertyIsEnumerable("toString")){var a=B;B=function(b,c){a(b,c);for(var d=0,e;(e=Vf[d])&&(!J(b,e)||!1!==c.call(b,b[e],e,b));d++);}}})();Object.getOwnPropertyNames||
Ze();zb(lb,{keys:function(a){var b=[];if(null==a)throw new TypeError("Object required");B(Ya(a),function(c,d){b.push(d)});return b}});zb(ca,{isArray:function(a){return P(a)}});Ua(ca,{every:function(a){var b=arguments[1],c=this.length,d=0;for(la(a);d<c;){if(d in this&&!a.call(b,this[d],d,this))return!1;d++}return!0},some:function(a){var b=arguments[1],c=this.length,d=0;for(la(a);d<c;){if(d in this&&a.call(b,this[d],d,this))return!0;d++}return!1},map:function(a){var b=arguments[1],c=this.length,d=0,
e=Array(c);for(la(a);d<c;)d in this&&(e[d]=a.call(b,this[d],d,this)),d++;return e},filter:function(a){var b=arguments[1],c=this.length,d=0,e=[];for(la(a);d<c;)d in this&&a.call(b,this[d],d,this)&&e.push(this[d]),d++;return e},indexOf:function(a){var b=arguments[1];return F(this)?this.indexOf(a,b):md(this,a,b)},lastIndexOf:function(a){var b=arguments[1];return F(this)?this.lastIndexOf(a,b):md(this,a,b,!0)},forEach:function(a){var b=arguments[1],c=this.length,d=0;for(la(a);d<c;)d in this&&a.call(b,
this[d],d,this),d++},reduce:function(a){return nd(this,a,arguments[1])},reduceRight:function(a){return nd(this,a,arguments[1],!0)}});var Wf=RegExp("^[\t\n\x0B\f\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u2028\u2029\u3000\ufeff]+|[\t\n\x0B\f\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u2028\u2029\u3000\ufeff]+$","g");Ua(ja,{trim:function(){return this.toString().replace(Wf,"")}});Ua(Kc,{bind:function(a){for(var b=
[],c=1,d=arguments.length;c<d;c++)b.push(arguments[c]);var e=this;la(this);c=function(){for(var f=[],g=0,h=arguments.length;g<h;g++)f.push(arguments[g]);return e.apply(e.prototype&&this instanceof e?this:a,b.concat(f))};c.prototype=this.prototype;return c}});zb(Y,{now:function(){return(new Date).getTime()}});Ua(Y,{toISOString:function(){return fa(this.getUTCFullYear(),4)+"-"+fa(this.getUTCMonth()+1,2)+"-"+fa(this.getUTCDate(),2)+"T"+fa(this.getUTCHours(),2)+":"+fa(this.getUTCMinutes(),2)+":"+fa(this.getUTCSeconds(),
2)+"."+fa(this.getUTCMilliseconds(),3)+"Z"},toJSON:function(a){return this.toISOString(a)}},!function(){var a=new Date(Date.UTC(2E3,0));return!!a.toISOString&&"2000-01-01T00:00:00.000Z"===a.toISOString()}());Ua(ja,{includes:function(a){var b=arguments[1],c=nc(this);a=oc(a);return-1!==c.indexOf(a,b)},startsWith:function(a){var b=arguments[1];var c=nc(this);a=oc(a);var d=c.length;b=sa(Q(+b||0,0),d);var e=a.length;return e+b>d?!1:c.substr(b,e)===a?!0:!1},endsWith:function(a){var b=arguments[1],c;var d=
nc(this);a=oc(a);var e=c=d.length;w(b)&&(e=+b||0);e=sa(Q(e,0),c);b=a.length;e-=b;return 0>e?!1:d.substr(e,b)===a?!0:!1},repeat:function(a){a=Oa(a);return Rb(this,a)}});zb(ta,{isNaN:function(a){return null!=a&&a!==a}});zb(ca,{from:function(a){var b=arguments[1],c=arguments[2];w(b)&&la(b);if(null==a)throw new TypeError("Object required.");a=Ya(a);var d=Z(Q(0,a.length||0));if(!Pb(d))throw new RangeError("Invalid array length");if(U(this)){var e=new this(d);e.length=d}else e=Array(d);for(var f=0;f<d;f++)L(e,
f,w(b)?b.call(c,a[f],f):a[f],!0);return e}});Ua(ca,{find:function(a){var b=arguments[1];la(a);for(var c=0,d=this.length;c<d;c++)if(a.call(b,this[c],c,this))return this[c]},findIndex:function(a){var b=arguments[1];la(a);for(var c=0,d=this.length;c<d;c++)if(a.call(b,this[c],c,this))return c;return-1}});Ua(ca,{includes:function(a){var b=arguments[1];if(F(this))return this.includes(a,b);b=b?b.valueOf():0;var c=this.length;for(0>b&&(b=Q(0,b+c));b<c;b++){var d=a,e=this[b];if(null!=d&&d!==d?null!=e&&e!==
e:d===e&&(0!==d||1/d===1/e))return!0}return!1}});var hf="months weekdays units numerals placeholders articles tokens timeMarkers ampm timeSuffixes parse timeParse timeFrontParse modifiers".split(" "),Xf=/(\w{3})[()\s\d]*$/,uc={yyyy:{h:"year",src:"\\d{4}"},MM:{h:"month",src:"[01]?\\d"},dd:{h:"date",src:"[0123]?\\d"},hh:{h:"hour",src:"[0-2]?\\d"},mm:{h:"minute",src:"[0-5]\\d"},ss:{h:"second",src:"[0-5]\\d(?:[,.]\\d+)?"},yy:{h:"year",src:"\\d{2}"},y:{h:"year",src:"\\d"},yearSign:{src:"[+-]",sign:!0},
tzHour:{src:"[0-1]\\d"},tzMinute:{src:"[0-5]\\d"},tzSign:{src:"[+\u2212-]",sign:!0},ihh:{h:"hour",src:"[0-2]?\\d(?:[,.]\\d+)?"},imm:{h:"minute",src:"[0-5]\\d(?:[,.]\\d+)?"},GMT:{h:"utc",src:"GMT",C:1},Z:{h:"utc",src:"Z",C:1},timestamp:{src:"\\d+"}},Cd={year:{i:"yyyy",A:!0},month:{i:"MM",A:!0},date:{i:"dd",A:!0},hour:{i:"hh",J:":"},minute:{i:"mm"},second:{i:"ss"},num:{src:"\\d+",Y:!0}},jf=[{src:"{MM}[-.\\/]{yyyy}"},{time:!0,src:"{dd}[-.\\/]{MM}(?:[-.\\/]{yyyy|yy|y})?",mdy:"{MM}[-.\\/]{dd}(?:[-.\\/]{yyyy|yy|y})?"},
{time:!0,src:"{yyyy}[-.\\/]{MM}(?:[-.\\/]{dd})?"},{src:"\\\\/Date\\({timestamp}(?:[+-]\\d{4,4})?\\)\\\\/"},{src:"{yearSign?}{yyyy}(?:-?{MM}(?:-?{dd}(?:T{ihh}(?::?{imm}(?::?{ss})?)?)?)?)?{tzOffset?}"}],zd={ISO8601:"{yyyy}-{MM}-{dd}T{HH}:{mm}:{ss}.{SSS}{Z}",RFC1123:"{Dow}, {dd} {Mon} {yyyy} {HH}:{mm}:{ss} {ZZ}",RFC1036:"{Weekday}, {dd}-{Mon}-{yy} {HH}:{mm}:{ss} {ZZ}"},Yf=[{b:"Dow",a:"a",j:"dow",get:function(a,b){return M.get(b).I(S(a),2)}},{b:"Weekday",a:"A",j:"weekday",D:!0,get:function(a,b,c){return M.get(b).I(S(a),
c)}},{b:"Mon",a:"b h",j:"mon",get:function(a,b){return M.get(b).H(ma(a),2)}},{b:"Month",a:"B",j:"month",D:!0,get:function(a,b,c){return M.get(b).H(ma(a),c)}},{a:"C",get:function(a){return ya(a).toString().slice(0,2)}},{b:"d date day",a:"d",g:2,c:"dd",l:"do",get:function(a){return qa(a)}},{a:"e",get:function(a){return fa(qa(a),2,!1,10," ")}},{b:"H 24hr",a:"H",g:2,c:"HH",get:function(a){return aa(a,"Hours")}},{b:"h hours 12hr",a:"I",g:2,c:"hh",get:function(a){return aa(a,"Hours")%12||12}},{b:"D",a:"j",
g:3,c:"DDD",get:function(a){var b=na(Ha(a),6);return Ub(a,b,Aa[4])+1}},{b:"M",a:"m",g:2,l:"Mo",c:"MM",get:function(a){return ma(a)+1}},{b:"m minutes",a:"M",g:2,c:"mm",get:function(a){return aa(a,"Minutes")}},{b:"Q",get:function(a){return Ba((ma(a)+1)/3)}},{b:"TT",a:"p",get:function(a,b){return sc(a,b)}},{b:"tt",a:"P",get:function(a,b){return sc(a,b).toLowerCase()}},{b:"T",j:"t",get:function(a,b){return sc(a,b).charAt(0)}},{b:"s seconds",a:"S",g:2,c:"ss",get:function(a){return aa(a,"Seconds")}},{b:"S ms",
g:3,c:"SSS",get:function(a){return aa(a,"Milliseconds")}},{b:"e",a:"u",l:"eo",get:function(a){return S(a)||7}},{a:"U",g:2,get:function(a){return eb(a,!1,0)}},{b:"W",a:"V",g:2,l:"Wo",c:"WW",get:function(a){return eb(a,!0)}},{a:"w",get:function(a){return S(a)}},{b:"w",l:"wo",c:"ww",get:function(a,b){var c=M.get(b),d=c.s(b);return eb(a,!0,d,c.G(b))}},{a:"W",g:2,get:function(a){return eb(a,!1)}},{c:"gggg",u:"gg",get:function(a,b){return vd(a,b)}},{a:"G",g:4,B:"g",c:"GGGG",u:"GG",get:function(a,b){return vd(a,
b,!0)}},{b:"year",c:"yyyy",u:"yy",a:"Y",g:4,B:"y",get:function(a){return ya(a)}},{b:"ZZ",a:"z",get:function(a){return pc(a)}},{b:"X",get:function(a){return Z(a.getTime()/1E3)}},{b:"x",get:function(a){return a.getTime()}},{b:"Z",get:function(a){return pc(a,!0)}},{b:"z",a:"Z",get:function(a){return(a=a.toString().match(Xf))?a[1]:""}},{a:"D",alias:"%m/%d/%y"},{a:"F",alias:"%Y-%m-%d"},{a:"r",alias:"%I:%M:%S %p"},{a:"R",alias:"%H:%M"},{a:"T",alias:"%H:%M:%S"},{a:"x",alias:"{short}"},{a:"X",alias:"{time}"},
{a:"c",alias:"{stamp}"}],Aa=[{name:"millisecond",method:"Milliseconds",f:1,start:0,end:999},{name:"second",method:"Seconds",f:1E3,start:0,end:59},{name:"minute",method:"Minutes",f:6E4,start:0,end:59},{name:"hour",method:"Hours",f:36E5,start:0,end:23},{name:"day",alias:"date",method:"Date",m:!0,f:864E5,start:1,end:function(a){return pd(a)}},{name:"week",method:"ISOWeek",m:!0,f:6048E5},{name:"month",method:"Month",m:!0,f:26298E5,start:0,end:11},{name:"year",method:"FullYear",m:!0,f:315576E5,start:0}],
af=hc(Y,{newDateInternal:function(){return new Date}}),da,Bb,Vb,Ta,M;Ma(Y,{create:function(a,b){return Ca(a,b)},getLocale:function(a){return M.get(a,!a)},getAllLocales:function(){return M.getAll()},getAllLocaleCodes:function(){return Object.keys(M.getAll())},setLocale:function(a){return M.set(a)},addLocale:function(a,b){return M.add(a,b)},removeLocale:function(a){return M.remove(a)}});Ab(Y,{set:function(a,b){b=qd(b);return Ja(a,b[0],b[1])},advance:function(a,b){return sd(a,b,1)},rewind:function(a,
b){return sd(a,b,-1)}});T(Y,{get:function(a,b,c){return sb(a,b,c,void 0).date},setWeekday:function(a,b){return Ia(a,b)},setISOWeek:function(a,b){return ud(a,b)},getISOWeek:function(a){return eb(a,!0)},beginningOfISOWeek:function(a){var b=S(a);0===b?b=-6:1!==b&&(b=1);Ia(a,b);return na(a,3)},endOfISOWeek:function(a){0!==S(a)&&Ia(a,7);return Tb(a,4)},getUTCOffset:function(a,b){return pc(a,b)},setUTC:function(a,b){return ba(a,b)},isUTC:function(a){return!!ba(a)||0===a.getTimezoneOffset()},isValid:function(a){return!isNaN(a.getTime())},
isAfter:function(a,b,c){return a.getTime()>Ca(b).getTime()-(c||0)},isBefore:function(a,b,c){return a.getTime()<Ca(b).getTime()+(c||0)},isBetween:function(a,b,c,d){a=a.getTime();b=Ca(b).getTime();var e=Ca(c).getTime();c=sa(b,e);b=Q(b,e);d=d||0;return c-d<=a&&b+d>=a},isLeapYear:function(a){a=ya(a);return 0===a%4&&0!==a%100||0===a%400},daysInMonth:function(a){return pd(a)},format:function(a,b,c){return xd(a,b,c)},relative:function(a,b,c){return wd(a,null,b,c)},relativeTo:function(a,b,c){return wd(a,
Ca(b),c)},is:function(a,b,c){return Ad(a,b,c)},reset:function(a,b,c){b=b?df(b):4;rb(a,b,c);return a},clone:function(a){return Ha(a)},iso:function(a){return a.toISOString()},getWeekday:function(a){return S(a)},getUTCWeekday:function(a){return a.getUTCDay()}});T(ta,{duration:function(a,b){return M.get(b).O(a)}});var Lc={code:"en",plural:!0,timeMarkers:"at",ampm:"AM|A.M.|a,PM|P.M.|p",units:"millisecond:|s,second:|s,minute:|s,hour:|s,day:|s,week:|s,month:|s,year:|s",months:"Jan:uary|,Feb:ruary|,Mar:ch|,Apr:il|,May,Jun:e|,Jul:y|,Aug:ust|,Sep:tember|t|,Oct:ober|,Nov:ember|,Dec:ember|",
weekdays:"Sun:day|,Mon:day|,Tue:sday|,Wed:nesday|,Thu:rsday|,Fri:day|,Sat:urday|+weekend",numerals:"zero,one|first,two|second,three|third,four:|th,five|fifth,six:|th,seven:|th,eight:|h,nin:e|th,ten:|th",articles:"a,an,the",tokens:"the,st|nd|rd|th,of|in,a|an,on",time:"{H}:{mm}",past:"{num} {unit} {sign}",future:"{num} {unit} {sign}",duration:"{num} {unit}",modifiers:[{name:"half",src:"half",value:.5},{name:"midday",src:"noon",value:12},{name:"midday",src:"midnight",value:24},{name:"day",src:"yesterday",
value:-1},{name:"day",src:"today|tonight",value:0},{name:"day",src:"tomorrow",value:1},{name:"sign",src:"ago|before",value:-1},{name:"sign",src:"from now|after|from|in|later",value:1},{name:"edge",src:"first day|first|beginning",value:-2},{name:"edge",src:"last day",value:1},{name:"edge",src:"end|last",value:2},{name:"shift",src:"last",value:-1},{name:"shift",src:"the|this",value:0},{name:"shift",src:"next",value:1}],parse:"(?:just)? now;{shift} {unit:5-7};{months?} (?:{year}|'{yy});{midday} {4?} {day|weekday};{months},?(?:[-.\\/\\s]{year})?;{edge} of (?:day)? {day|weekday};{0} {num}{1?} {weekday} {2} {months},? {year?};{shift?} {day?} {weekday?} {timeMarker?} {midday};{sign?} {3?} {half} {3?} {unit:3-4|unit:7} {sign?};{0?} {edge} {weekday?} {2} {shift?} {unit:4-7?} {months?},? {year?}".split(";"),
timeParse:"{day|weekday};{shift} {unit:5?} {weekday};{0?} {date}{1?} {2?} {months?};{weekday} {2?} {shift} {unit:5};{0?} {num} {2?} {months}\\.?,? {year?};{num?} {unit:4-5} {sign} {day|weekday};{year}[-.\\/\\s]{months}[-.\\/\\s]{date};{0|months} {date?}{1?} of {shift} {unit:6-7};{0?} {num}{1?} {weekday} of {shift} {unit:6};{date}[-.\\/\\s]{months}[-.\\/\\s](?:{year}|'?{yy});{weekday?}\\.?,? {months}\\.?,? {date}{1?},? (?:{year}|'{yy})?".split(";"),timeFrontParse:["{sign} {num} {unit}","{num} {unit} {sign}",
"{4?} {day|weekday}"]},ue=oa(oa({},Lc),{mdy:!0,firstDayOfWeek:0,firstDayOfWeekYear:1,"short":"{MM}/{dd}/{yyyy}",medium:"{Month} {d}, {yyyy}","long":"{Month} {d}, {yyyy} {time}",full:"{Weekday}, {Month} {d}, {yyyy} {time}",stamp:"{Dow} {Mon} {d} {yyyy} {time}",time:"{h}:{mm} {TT}"}),ve=oa(oa({},Lc),{"short":"{dd}/{MM}/{yyyy}",medium:"{d} {Month} {yyyy}","long":"{d} {Month} {yyyy} {H}:{mm}",full:"{Weekday}, {d} {Month}, {yyyy} {time}",stamp:"{Dow} {d} {Mon} {yyyy} {time}"}),Zf=oa(oa({},Lc),{"short":"{yyyy}-{MM}-{dd}",
medium:"{d} {Month}, {yyyy}","long":"{d} {Month}, {yyyy} {H}:{mm}",full:"{Weekday}, {d} {Month}, {yyyy} {time}",stamp:"{Dow} {d} {Mon} {yyyy} {time}"}),we={"en-US":ue,"en-GB":ve,"en-AU":ve,"en-CA":Zf};(function(){function a(b){this.o={};this.add(b)}a.prototype={get:function(b,c){var d=this.o[b];!d&&we[b]?d=this.add(b,we[b]):!d&&b&&(d=this.o[b.slice(0,2)]);return d||!1===c?d:this.current},getAll:function(){return this.o},set:function(b){var c=this.get(b,!1);if(!c)throw new TypeError("Invalid Locale: "+
b);return this.current=c},add:function(b,c){c?c.code=b:(c=b,b=c.code);var d=c.compiledFormats?c:Ed(c);this.o[b]=d;this.current||(this.current=d);return d},remove:function(b){this.current.code===b&&(this.current=this.get("en"));return delete this.o[b]}};Ta=Ed(ue);M=new a(Ta)})();(function(){function a(k,l,m){l&&D(ua(l),function(n){k[n]=m})}function b(k){return function(l,m){return k(l,m).toLowerCase()}}function c(k){return function(l,m){var n=k(l,m);return n+M.get(m).S(n)}}function d(k,l){return function(m,
n){return fa(k(m,n),l)}}function e(k){return function(l,m){return k(l,m)%100}}function f(k){return function(l,m){return Vb(k,l,m)}}function g(k,l){function m(n,p){return k.get(n,p,l)}a(da,k.b+l,m);k.j&&(da[k.j+l]=b(m))}function h(k){return function(l,m){var n=M.get(m);return Vb(n[k],l,m)}}da={};Bb={};D(Yf,function(k){var l=k.get,m;k.j&&(da[k.j]=b(l));k.l&&(da[k.l]=c(l,k));k.c&&(da[k.c]=d(l,k.c.length));k.u&&(da[k.u]=d(e(l),2));k.B&&(Bb[k.B]=d(e(l),2));k.g&&(m=d(l,k.g));k.alias&&(l=f(k.alias));if(k.D)for(var n=
1;5>=n;n++)g(k,n);a(da,k.b,l);a(Bb,k.a,m||l)});B(zd,function(k,l){a(da,l,f(k))});Wa(Y,"short medium long full",function(k,l){var m=h(l);a(da,l,m);k[l]=m});a(da,"time",h("time"));a(da,"stamp",h("stamp"))})();(function(){Vb=kd(function(a,b,c){return A(da,b)(a,c)},function(a,b,c){return A(Bb,b)(a,c)},function(a,b){return J(da,a)||J(Bb,b)})})();(function(){Wa(Y,Aa,function(a,b,c){var d=b.name,e=$a(d);4<c&&D(["Last","This","Next"],function(f){a["is"+f+e]=function(g,h){return Bd(g,f+" "+d,0,h,{locale:"en"})}});
3<c&&(a["beginningOf"+e]=function(f,g){return rb(f,c,g)},a["endOf"+e]=function(f,g){return Tb(f,c,g)});a["add"+e+"s"]=function(f,g,h){return Sa(f,d,g,h)};a[d+"sAgo"]=a[d+"sUntil"]=function(f,g,h){return Ub(sb(f,g,h,!0).date,f,b)};a[d+"sSince"]=a[d+"sFromNow"]=function(f,g,h){return Ub(f,sb(f,g,h,!0).date,b)}})})();(function(){Wa(ta,Aa,function(a,b){var c=b.name;var d=function(g){return ob(g*b.f)};var e=function(g,h,k){return Sa(Ca(h,k,!0),c,g)};var f=function(g,h,k){return Sa(Ca(h,k,!0),c,-g)};a[c]=
d;a[c+"s"]=d;a[c+"Before"]=f;a[c+"sBefore"]=f;a[c+"Ago"]=f;a[c+"sAgo"]=f;a[c+"After"]=e;a[c+"sAfter"]=e;a[c+"FromNow"]=e;a[c+"sFromNow"]=e})})();(function(){var a=ua("Today Yesterday Tomorrow Weekday Weekend Future Past"),b=Ta.weekdays.slice(0,7),c=Ta.months.slice(0,12);Wa(Y,a.concat(b).concat(c),function(d,e){d["is"+e]=function(f){return Ad(f,e)}})})();bd(Y,Ca);var nf=/[^\u0000-\u0040\u005B-\u0060\u007B-\u007F]+('s)?/g,mf=/(^|_)([^_]+)/g,sf=/&#?(x)?([\w\d]{0,5});/gi,$f=/[&<>]/g,Id={lt:"<",gt:">",
amp:"&",nbsp:" ",quot:'"',apos:"'"},Mc,pf="and or nor a an the so but to of at by from into on onto off out in over with for".split(" "),tf="area base br col command embed hr img input keygen link meta param source track wbr".split(" "),ag=RegExp("^[\t\n\x0B\f\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u2028\u2029\u3000\ufeff]+"),bg=RegExp("[\t\n\x0B\f\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u2028\u2029\u3000\ufeff]+$"),
qf=RegExp("(?=[\t\n\x0B\f\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u2028\u2029\u3000\ufeff])"),cg=String.prototype.includes,Nc,Oc,dg=kd(Jb);T(ja,{includes:va(function(a,b,c){if(!xa(b))return cg.call(a,b,c);c&&(a=a.slice(c));return b.test(a)})},["enhance","enhanceString"]);T(ja,{at:function(a,b,c){return gd(a,b,c,!0)},escapeURL:function(a,b){return b?encodeURIComponent(a):encodeURI(a)},unescapeURL:function(a,b){return b?decodeURI(a):decodeURIComponent(a)},
escapeHTML:function(a){return a.replace($f,function(b){return A(Mc,b)})},unescapeHTML:function(a){return rf(a)},stripTags:function(a,b,c){return Kd(a,b,c,!0)},removeTags:function(a,b,c){return Kd(a,b,c,!1)},encodeBase64:function(a){return Nc(a)},decodeBase64:function(a){return Oc(a)},forEach:function(a,b,c){return ub(a,b,c)},chars:function(a,b,c){return ub(a,b,c)},words:function(a,b){return ub(a.trim(),/\S+/g,b)},lines:function(a,b){return ub(a.trim(),/^.*$/gm,b)},codes:function(a,b){return Hd(a,
b)},shift:function(a,b){var c="";b=b||0;Hd(a,function(d){c+=X(d+b)});return c},isBlank:function(a){return 0===a.trim().length},isEmpty:function(a){return 0===a.length},insert:function(a,b,c){c=E(c)?a.length:c;return a.slice(0,c)+b+a.slice(c)},remove:function(a,b){return a.replace(b,"")},removeAll:function(a,b){return Jd(a,b)},reverse:function(a){return a.split("").reverse().join("")},compact:function(a){return a.trim().replace(/([\r\n\s\u3000])+/g,function(b,c){return"\u3000"===c?c:" "})},from:function(a,
b){return a.slice(Md(a,b,!0))},to:function(a,b){E(b)&&(b=a.length);return a.slice(0,Md(a,b))},dasherize:function(a){return vb(a).replace(/_/g,"-")},underscore:function(a){return vb(a)},camelize:function(a,b){return lf(a,b)},spacify:function(a){return vb(a).replace(/_/g," ")},titleize:function(a){return of(a)},parameterize:function(a,b){var c=b;void 0===c&&(c="-");var d=a.replace(/[^a-z0-9\-_]+/gi,c);c&&(c=RegExp(["^","+|","+$|(",")","+"].join(bb(c)),"g"),d=d.replace(c,"$1"));return encodeURI(d.toLowerCase())},
truncate:function(a,b,c,d){return Gd(a,b,c,d)},truncateOnWord:function(a,b,c,d){return Gd(a,b,c,d,!0)},pad:function(a,b,c){b=Oa(b);var d=Q(0,b-a.length)/2;b=db(d);d=Ba(d);return Xb(b,c)+a+Xb(d,c)},padLeft:function(a,b,c){b=Oa(b);return Xb(Q(0,b-a.length),c)+a},padRight:function(a,b,c){b=Oa(b);return a+Xb(Q(0,b-a.length),c)},first:function(a,b){E(b)&&(b=1);return a.substr(0,b)},last:function(a,b){E(b)&&(b=1);return a.substr(0>a.length-b?0:a.length-b)},toNumber:function(a,b){return mc(a,b)},capitalize:function(a,
b,c){return vc(a,b,c)},trimLeft:function(a){return a.replace(ag,"")},trimRight:function(a){return a.replace(bg,"")}});Ab(ja,{replaceAll:function(a,b,c){return Jd(a,b,c)},format:function(a,b){var c=b[0]&&b[0].valueOf();1===b.length&&V(c)&&(b=c);return dg(a,b)}});(function(){function a(e){return function(f){try{return e(f)}catch(g){return""}}}if("undefined"!==typeof Buffer)Nc=function(e){return(new Buffer(e)).toString("base64")},Oc=function(e){return(new Buffer(e,"base64")).toString("utf8")};else{if("undefined"!==
typeof btoa){var b=a(btoa);var c=a(atob)}else{var d=/[^A-Za-z0-9\+\/=]/g;b=function(e){var f="",g=0;do{var h=e.charCodeAt(g++);var k=e.charCodeAt(g++);var l=e.charCodeAt(g++);var m=h>>2;h=(h&3)<<4|k>>4;var n=(k&15)<<2|l>>6;var p=l&63;isNaN(k)?n=p=64:isNaN(l)&&(p=64);f+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(m);f+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(h);f+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(n);
f+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(p)}while(g<e.length);return f};c=function(e){var f="",g=0;if(e.match(d))return"";e=e.replace(/[^A-Za-z0-9\+\/=]/g,"");do{var h="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(e.charAt(g++));var k="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(e.charAt(g++));var l="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(e.charAt(g++));var m="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(e.charAt(g++));
h=h<<2|k>>4;k=(k&15)<<4|l>>2;var n=(l&3)<<6|m;f+=X(h);64!=l&&(f+=X(k));64!=m&&(f+=X(n))}while(g<e.length);return f}}Nc=function(e){return b(unescape(encodeURIComponent(e)))};Oc=function(e){return decodeURIComponent(escape(c(e)))}}})();(function(){Mc={};B(Id,function(a,b){Mc[a]="&"+b+";"})})();var eg=!("0"in[].concat(void 0).concat()),fg={sortIgnore:null,sortNatural:!0,sortIgnoreCase:!0,sortOrder:function(){return Ga("A\u00c1\u00c0\u00c2\u00c3\u0104BC\u0106\u010c\u00c7D\u010e\u00d0E\u00c9\u00c8\u011a\u00ca\u00cb\u0118FG\u011eH\u0131I\u00cd\u00cc\u0130\u00ce\u00cfJKL\u0141MN\u0143\u0147\u00d1O\u00d3\u00d2\u00d4PQR\u0158S\u015a\u0160\u015eT\u0164U\u00da\u00d9\u016e\u00db\u00dcVWXY\u00ddZ\u0179\u017b\u017d\u00de\u00c6\u0152\u00d8\u00d5\u00c5\u00c4\u00d6".split(""),
function(a){return a+a.toLowerCase()}).join("")}(),sortCollate:function(a,b){var c=0,d=0,e=gb("sortOrder");var f=gb("sortIgnore");var g=gb("sortNatural");var h=gb("sortIgnoreCase");var k=gb("sortEquivalents");a=Td(a,f,h);b=Td(b,f,h);do{var l=Ud(a,c,k);var m=Ud(b,c,k);f=l?e.indexOf(l):null;h=m?e.indexOf(m):null;-1===f||-1===h?(f=a.charCodeAt(c)||null,h=b.charCodeAt(c)||null,g&&(48<=f&&57>=f||65296<=f&&65305>=f)&&(48<=h&&57>=h||65296<=h&&65305>=h)&&(f=mc(a.slice(c)),h=mc(b.slice(c)))):(l=l!==a.charAt(c),
m=m!==b.charAt(c),l!==m&&0===d&&(d=l-m));c+=1}while(null!=f&&null!=h&&f===h);return f===h?d:f-h},sortEquivalents:function(){var a={};D(ua("A\u00c1\u00c0\u00c2\u00c3\u00c4 C\u00c7 E\u00c9\u00c8\u00ca\u00cb I\u00cd\u00cc\u0130\u00ce\u00cf O\u00d3\u00d2\u00d4\u00d5\u00d6 S\u00df U\u00da\u00d9\u00db\u00dc"),function(b){var c=b.charAt(0);D(b.slice(1).split(""),function(d){a[d]=c;a[d.toLowerCase()]=c.toLowerCase()})});return a}()},gb=hc(ca,fg);Ma(ca,{create:function(a,b){return Nd(a,b)},construct:function(a,
b){a=Oa(a);return Array.from(Array(a),function(c,d){return b&&b(d)})}});T(ca,{isEmpty:function(a){return 0===a.length},isEqual:function(a,b){return Pa(a,b)},clone:function(a){return fb(a)},at:function(a,b,c){return gd(a,b,c)},add:function(a,b,c){return Od(fb(a),b,c)},subtract:function(a,b){return Rd(a,b,!0)},append:function(a,b,c){return Od(a,b,c)},removeAt:function(a,b,c){if(E(b))return a;E(c)&&(c=b);a.splice(b,c-b+1);return a},unique:function(a,b){return Pd(a,b)},flatten:function(a,b){return Qd(a,
b)},first:function(a,b){if(E(b))return a[0];0>b&&(b=0);return a.slice(0,b)},last:function(a,b){return E(b)?a[a.length-1]:a.slice(0>a.length-b?0:a.length-b)},from:function(a,b){return a.slice(b)},to:function(a,b){E(b)&&(b=a.length);return a.slice(0,b)},compact:function(a,b){return wf(a,b)},groupBy:function(a,b,c){return xf(a,b,c)},inGroups:function(a,b,c){var d=w(c),e=Array(b),f=Ba(a.length/b);Kb(b,function(g){var h=g*f,k=a.slice(h,h+f);d&&k.length<f&&Kb(f-k.length,function(){k.push(c)});e[g]=k});
return e},inGroupsOf:function(a,b,c){var d=[],e=a.length,f;if(0===e||0===b)return a;E(b)&&(b=1);E(c)&&(c=null);Kb(Ba(e/b),function(g){for(f=a.slice(b*g,b*g+b);f.length<b;)f.push(c);d.push(f)});return d},shuffle:function(a){a=fb(a);for(var b=a.length,c,d;b;)c=Math.random()*b|0,d=a[--b],a[b]=a[c],a[c]=d;return a},sample:function(a,b,c){var d=[];if(!hb(b)){var e=b;b=c}if(E(e)){e=1;var f=!0}b||(a=fb(a));e=sa(e,a.length);for(b=0;b<e;b++)c=Z(Math.random()*a.length),d.push(a[c]),a.splice(c,1);return f?d[0]:
d},sortBy:function(a,b,c){a.sort(function(d,e){var f=Fa(d,b,a,[d]),g=Fa(e,b,a,[e]);return Sd(f,g)*(c?-1:1)});return a},remove:function(a,b){for(var c=wa(b),d=0;d<a.length;)c(a[d],d,a)?a.splice(d,1):d++;return a},exclude:function(a,b){for(var c=[],d=wa(b),e=0;e<a.length;e++)d(a[e],e,a)||c.push(a[e]);return c},union:function(a,b){var c=eg?vf(a,b):a.concat(b);return Pd(c)},intersect:function(a,b){return Rd(a,b,!1)}});Ab(ca,{zip:function(a,b){return Ga(a,function(c,d){return[c].concat(Ga(b,function(e){return d in
e?e[d]:null}))})}});te(ca,"insert","append");bd(ca,Nd);var Af=/^(.+?)(\[.*\])$/,Df=/[^\d.-]/,Ac=Object.getOwnPropertyNames,Xd=Object.getOwnPropertySymbols,Yd=Object.getOwnPropertyDescriptor;fc=Object.prototype.toString;Ma(lb,{fromQueryString:function(a,b){return zf(a,b)}});gc(lb,{has:function(a,b,c){return Xa(a,b,c,!0)},get:function(a,b,c){return Jb(a,b,c)},set:function(a,b,c){Xa(a,b,!1,!1,!0,!1,c);return a},size:function(a){return Object.keys(Ya(a)).length},isEmpty:function(a){return 0===Object.keys(Ya(a)).length},
toQueryString:function(a,b){var c=b||{};E(c.separator)&&(c.separator="_");return wc(a,c.deep,c.transform,c.prefix||"",c.separator)},isEqual:function(a,b){return Pa(a,b)},merge:function(a,b,c){return yc(a,b,c)},add:function(a,b,c){return yc(Bc(a),b,c)},mergeAll:function(a,b,c){return zc(a,b,c)},addAll:function(a,b,c){return zc(Bc(a),b,c)},defaults:function(a,b,c){c=c||{};c.resolve=c.resolve||!1;return zc(a,b,c)},intersect:function(a,b){return ae(a,b,!1)},subtract:function(a,b){return ae(a,b,!0)},clone:function(a,
b){return Bc(a,b)},values:function(a){return Ff(a)},invert:function(a,b){var c={};b=!0===b;B(a,function(d,e){J(c,d)&&b?c[d].push(e):c[d]=b?[e]:e});return c},tap:function(a,b){return Gf(a,b)},isArguments:function(a){var b=ka(a);return!Ea(a)&&"length"in a&&("[object Arguments]"===b||!!a.callee)},isObject:function(a){return Ib(a)},remove:function(a,b){return Hf(a,b)},exclude:function(a,b){return If(a,b)},select:function(a,b){return $d(a,b,!0)},reject:function(a,b){return $d(a,b,!1)}});T(lb,{keys:function(a){return Object.keys(a)}});
(function(){var a=[hb,R,F,ia,xa,U,P,Ob,Mb,Nb];Le(lb,"Boolean Number String Date RegExp Function Array Error Set Map",function(b,c,d){b["is"+c]=a[d]})})();var gg=ib("map",fe),hg=ib("find",La),xe=ib("some",La),ig=ib("every",La),ye=ib("filter",La),jg=ib("findIndex",La);T(ca,{map:va(gg),some:va(xe),every:va(ig),filter:va(ye),find:va(hg),findIndex:va(jg)},["enhance","enhanceArray"]);T(ca,{none:va(function(){return!xe.apply(this,arguments)}),count:va(function(a,b){return E(b)?a.length:ye.apply(this,arguments).length}),
min:function(a,b,c){return xb(a,b,c)},max:function(a,b,c){return xb(a,b,c,!0)},least:function(a,b,c){return Zb(a,b,c)},most:function(a,b,c){return Zb(a,b,c,!0)},sum:function(a,b){return be(a,b)},average:function(a,b){return ce(a,b)},median:function(a,b){return de(a,b)}});var ze=Cc("some"),kg=Cc("find"),lg=Cc("every");gc(lb,{forEach:function(a,b){return Jf(a,b)},map:function(a,b){return Kf(a,b)},some:ze,every:lg,filter:function(a,b){return Mf(a,b)},reduce:function(a,b,c){return Lf(a,b,c)},find:kg,
count:function(a,b){return Nf(a,b)},none:function(a,b){return!ze(a,b)},sum:function(a,b){return be(a,b)},average:function(a,b){return ce(a,b)},median:function(a,b){return de(a,b)},min:function(a,b,c){return xb(a,b,c,!1,!0)},max:function(a,b,c){return xb(a,b,c,!0,!0)},least:function(a,b,c){return Zb(a,b,c,!1,!0)},most:function(a,b,c){return Zb(a,b,c,!0,!0)}});(function(){function a(f,g,h){var k=f;g&&(k=f.slice(g),h&&(k=k.concat(f.slice(0,g))));return k}function b(f,g){return sa(g,Q(0,f))}function c(f,
g,h,k,l,m){return function(n,p,q){q=kc(q+g,l,m);return h.call(f,n,p,q,f)}}function d(f,g,h,k,l,m){return function(n,p){p=kc(p+g,l,m);return h.call(k,f[p],p,f)}}function e(f,g){var h=g.i||Array.prototype[f],k=g.apply||d,l=g.slice||a,m=g.clamp||b,n=g.result,p=g.v;return function(q,t,x){var v=[],u=0,r;var y=q.length;hb(x[0])&&(r=x[u++]);var z=x[u++];u=x[u];0>t&&(t+=y);t=m(t,y);ad(x.length);z=p?p(z,u):z;v.push(k(q,t,z,u,y,r));u&&v.push(u);q=h.apply(l(q,t,r),v);n&&(q=n(q,t,y));return q}}B({forEach:{i:function(f){D(this,
f)}},map:{v:fe},"some every":{v:La},findIndex:{v:La,result:function(f,g,h){-1!==f&&(f=(f+g)%h);return f}},reduce:{apply:c},"filter find":{v:La},reduceRight:{apply:c,slice:function(f,g,h){h||(f=f.slice(0,Q(0,g+1)));return f},clamp:function(f,g){return sa(g,Q(-1,f))}}},function(f,g){D(ua(g),function(h){var k=h+"FromIndex";h=e(h,f);Ab(ca,k,h)})})})();var he=hc(ta,{decimal:".",thousands:","});Ma(ta,{random:function(a,b){1==arguments.length&&(b=a,a=0);var c=sa(a||0,E(b)?1:b);var d=Q(a||0,E(b)?1:b)+1;return Z(Math.random()*
(d-c)+c)}});T(ta,{isInteger:function(a){return 0===a%1},isOdd:function(a){return 0===a%1&&0!==a%2},isEven:function(a){return 0===a%2},isMultipleOf:function(a,b){return 0===a%b},log:function(a,b){return Math.log(a)/(b?Math.log(b):1)},abbr:function(a,b){return Dc(a,b,"|kmbt")},metric:function(a,b,c){"all"===c?c="yzafpn\u03bcm|KMGTPEZY":c||(c="n\u03bcm|k");return Dc(a,b,c)},bytes:function(a,b,c,d){"binary"===d||!d&&c?d="|,Ki,Mi,Gi,Ti,Pi,Ei":"si"!==d&&d||(d="|KMGTPE");return Dc(a,b,d,c)+"B"},format:function(a,
b){return ge(a,b)},hex:function(a,b){return fa(a,b||1,!1,16)},times:function(a,b){for(var c,d,e=0;e<a;e++)d=b.call(a,e),w(d)&&(c||(c=[]),c.push(d));return c},chr:function(a){return X(a)},pad:function(a,b,c,d){return fa(a,b,c,d)},ordinalize:function(a){var b=+pa(a).toString().slice(-2);return a+id(b)},toNumber:function(a){return a.valueOf()},round:Ec(ob),ceil:Ec(Ba),floor:Ec(db)});(function(){Wa(ta,"abs pow sin asin cos acos tan atan exp pow sqrt",function(a,b){a[b]=function(c,d){return Math[b](c.valueOf(),
d)}})})();var dc=mb("lock"),$b=mb("timers"),Ae=mb("partial"),Fc=mb("canceled"),mg=Object.create||function(a){function b(){}b.prototype=a;return new b};T(Kc,{lazy:function(a,b,c,d){return je(a,b,c,d)},throttle:function(a,b){return je(a,b,!0,1)},debounce:function(a,b){function c(){for(var d=[],e=0,f=arguments.length;e<f;e++)d.push(arguments[e]);ie(c);jb(c,b,a,this,d)}return c},cancel:function(a){return ie(a)},after:function(a,b){var c=0,d=[];b=Oa(b);return function(){for(var e=[],f=0,g=arguments.length;f<
g;f++)e.push(arguments[f]);d.push(e);c++;if(c>=b)return a.call(this,d)}},once:function(a){var b=!1,c;return function(){if(b)return c;b=!0;return c=a.apply(this,arguments)}},memoize:function(a,b,c){if(!R(b)){var d=b;b=c}if(F(d)){var e=d;d=function(f){return Jb(f,e)}}else d||(d=Of);return Pf(a,d,b)},lock:function(a,b){if(Ae(a))return dc(a,R(b)?b:null),a;var c=function(){arguments.length=sa(dc(c),arguments.length);return a.apply(this,arguments)};dc(c,R(b)?b:a.length);return c}});Ab(Kc,{partial:function(a,
b){function c(){var e=0,f=[],g=this,h=dc(c),k;for(k=0;k<d;k++){var l=b[k];w(l)?f[k]=l:f[k]=arguments[e++]}for(k=e;k<arguments.length;k++)f.push(arguments[k]);null===h&&(h=d);R(h)&&(f.length=sa(f.length,h));return g instanceof c?(g=mg(a.prototype),e=a.apply(g,f),V(e)?e:g):a.apply(g,f)}var d=b.length;Ae(c,!0);return c},delay:function(a,b,c){jb(a,b,a,a,c);return a},every:function(a,b,c){function d(){jb(a,b,d);a.apply(a,c)}jb(a,b,d);return a}});Ma(se,{escape:function(a){return bb(a)}});T(se,{getFlags:function(a){return ab(a)},
setFlags:function(a,b){return RegExp(a.source,b)},addFlags:function(a,b){return RegExp(a.source,ab(a,b))},removeFlags:function(a,b){var c=RegExp("["+b+"]","g");return RegExp(a.source,ab(a).replace(c,""))}});var Rf=/(\d+)?\s*(year|month|week|day|hour|minute|second|millisecond)s?/i,qe={Hours:36E5,Minutes:6E4,Seconds:1E3,Milliseconds:1};$c(ea,{toString:function(){return ac(this)?this.start+".."+this.end:"Invalid Range"},isValid:function(){return ac(this)},span:function(){var a=ke(this.end)-ke(this.start);
return ac(this)?pa(a)+1:NaN},contains:function(a){return null==a?!1:a.start&&a.end?a.start>=this.start&&a.start<=this.end&&a.end>=this.start&&a.end<=this.end:a>=this.start&&a<=this.end},every:function(a,b){return bc(this,a,!1,b)},toArray:function(){return bc(this)},union:function(a){return new ea(this.start<a.start?this.start:a.start,this.end>a.end?this.end:a.end)},intersect:function(a){return a.start>this.end||a.end<this.start?new ea(NaN,NaN):new ea(this.start>a.start?this.start:a.start,this.end<
a.end?this.end:a.end)},clone:function(){return new ea(this.start,this.end)},clamp:function(a){return Hc(this,a)}});Ma(ta,{range:Qc});T(ta,{upto:function(a,b,c,d){return bc(new ea(a,b),c,!1,d)},clamp:function(a,b,c){return Hc(new ea(b,c),a)},cap:function(a,b){return Hc(new ea(void 0,b),a)}});te(ta,"downto","upto");Ma(ja,{range:Qc});var ng=/(?:from)?\s*(.+)\s+(?:to|until)\s+(.+)$/i,og=/(.+)\s*for\s*((?:\d+)?\s*(?:year|month|week|day|hour|minute|second|millisecond))s?/i,pg=/(?:for)?\s*((?:\d+)?\s*(?:year|month|week|day|hour|minute|second|millisecond))s?\s*(?:starting)?\s(?:at\s)?(.+)/i;
Ma(Y,{range:function(a,b){var c;if(1===arguments.length&&F(a))if(Y.get&&(c=a.match(ng))){var d=kb(c[1].replace("from","at"));var e=Y.get(d,c[2]);c=new ea(d,e)}else{if(c=a.match(pg)){var f=c[1];d=c[2]}if(c=a.match(og))d=c[1],f=c[2];d&&f?(d=kb(d),c=oe(f),e=pe(d,c[0],c[1])):d=a;c=new ea(kb(d),kb(e))}else c=new ea(kb(a),kb(b));return c}});(function(){var a={};D("year month week day hour minute second millisecond".split(" "),function(b,c){var d=b+"s";if(4>c)var e=function(){return bc(this,b,!0)};else{var f=
qe[$a(d)];e=function(){return Z((this.end-this.start)/f)}}a[d]=e});$c(ea,a)})();var Ic,Pc;T(ja,{pluralize:function(a,b){a=String(a);return 1===b||0===a.length?a:Pc("plural",a)},singularize:function(a){return Pc("singular",String(a))},humanize:function(a){a=qg(a);a=a.replace(/(_)?([a-z\d]*)/gi,function(b,c,d){d=N.human&&N.human.find(d)||d;d=N.acronyms&&N.acronyms.find(d)||d.toLowerCase();return(c?" ":"")+d});return $a(a)}});Zc(ja,"addAcronym",function(a){yb("acronyms",a,a);yb("acronyms",a.toLowerCase(),
a);Tf()});L(ja,"addPlural",I);L(ja,"addHuman",re);(function(){Ic=function(){this.map={};this.rules=[]};Ic.prototype={add:function(a,b){F(a)?this.map[a]=b:this.rules.unshift({K:a,X:b})},V:function(a){a=a.split(" ");var b=a.length-1;var c=a[b];a[b]=this.find(c)||this.L(c);return a.join(" ")},find:function(a){return A(this.map,a)},L:function(a){for(var b=0,c;c=this.rules[b];b++)if(c.K.test(a)){a=a.replace(c.K,c.X);break}return a}}})();(function(){Pc=function(a,b){return N[a]&&N[a].V(b)||b};I(/$/,"s");
I(/s$/i,"s");I(/(ax|test)is$/i,"$1es");I(/(octop|fung|foc|radi|alumn|cact)(i|us)$/i,"$1i");I(/(census|alias|status|fetus|genius|virus)$/i,"$1es");I(/(bu)s$/i,"$1ses");I(/(buffal|tomat)o$/i,"$1oes");I(/([ti])um$/i,"$1a");I(/([ti])a$/i,"$1a");I(/sis$/i,"ses");I(/f+e?$/i,"ves");I(/(cuff|roof)$/i,"$1s");I(/([ht]ive)$/i,"$1s");I(/([^aeiouy]o)$/i,"$1es");I(/([^aeiouy]|qu)y$/i,"$1ies");I(/(x|ch|ss|sh)$/i,"$1es");I(/(tr|vert)(?:ix|ex)$/i,"$1ices");I(/([ml])ouse$/i,"$1ice");I(/([ml])ice$/i,"$1ice");I(/^(ox)$/i,
"$1en");I(/^(oxen)$/i,"$1");I(/(quiz)$/i,"$1zes");I(/(phot|cant|hom|zer|pian|portic|pr|quart|kimon)o$/i,"$1os");I(/(craft)$/i,"$1");I(/([ft])[eo]{2}(th?)$/i,"$1ee$2");H(/s$/i,"");H(/([pst][aiu]s)$/i,"$1");H(/([aeiouy])ss$/i,"$1ss");H(/(n)ews$/i,"$1ews");H(/([ti])a$/i,"$1um");H(/((a)naly|(b)a|(d)iagno|(p)arenthe|(p)rogno|(s)ynop|(t)he)ses$/i,"$1$2sis");H(/(^analy)ses$/i,"$1sis");H(/(i)(f|ves)$/i,"$1fe");H(/([aeolr]f?)(f|ves)$/i,"$1f");H(/([ht]ive)s$/i,"$1");H(/([^aeiouy]|qu)ies$/i,"$1y");H(/(s)eries$/i,
"$1eries");H(/(m)ovies$/i,"$1ovie");H(/(x|ch|ss|sh)es$/i,"$1");H(/([ml])(ous|ic)e$/i,"$1ouse");H(/(bus)(es)?$/i,"$1");H(/(o)es$/i,"$1");H(/(shoe)s?$/i,"$1");H(/(cris|ax|test)[ie]s$/i,"$1is");H(/(octop|fung|foc|radi|alumn|cact)(i|us)$/i,"$1us");H(/(census|alias|status|fetus|genius|virus)(es)?$/i,"$1");H(/^(ox)(en)?/i,"$1");H(/(vert)(ex|ices)$/i,"$1ex");H(/tr(ix|ices)$/i,"trix");H(/(quiz)(zes)?$/i,"$1");H(/(database)s?$/i,"$1");H(/ee(th?)$/i,"oo$1");Da("person","people");Da("man","men");Da("human",
"humans");Da("child","children");Da("sex","sexes");Da("move","moves");Da("save","saves");Da("goose","geese");Da("zombie","zombies");Sf("equipment information rice money species series fish deer sheep jeans")})();var qg=ld;re(/_id$/g,"");var Be=/[\u0020-\u00A5]|[\uFF61-\uFF9F][\uff9e\uff9f]?/g,rg=/[\u2212\u3000-\u301C\u301A-\u30FC\uFF01-\uFF60\uFFE0-\uFFE6]/g,sg=/[\u30ab\u30ad\u30af\u30b1\u30b3\u30b5\u30b7\u30b9\u30bb\u30bd\u30bf\u30c1\u30c4\u30c6\u30c8\u30cf\u30d2\u30d5\u30d8\u30db]/,tg=/[\u30cf\u30d2\u30d5\u30d8\u30db\u30f2]/,
ug=[{name:"Arabic",src:"\u0600-\u06ff"},{name:"Cyrillic",src:"\u0400-\u04ff"},{name:"Devanagari",src:"\u0900-\u097f"},{name:"Greek",src:"\u0370-\u03ff"},{name:"Hangul",src:"\uac00-\ud7af\u1100-\u11ff"},{name:"Han Kanji",src:"\u4e00-\u9fff\uf900-\ufaff"},{name:"Hebrew",src:"\u0590-\u05ff"},{name:"Hiragana",src:"\u3040-\u309f\u30fb-\u30fc"},{name:"Kana",src:"\u3040-\u30ff\uff61-\uff9f"},{name:"Katakana",src:"\u30a0-\u30ff\uff61-\uff9f"},{name:"Latin",src:"\u0001-\u007f\u0080-\u00ff\u0100-\u017f\u0180-\u024f"},
{name:"Thai",src:"\u0e00-\u0e7f"}],vg=[{type:"a",start:65,end:90},{type:"a",start:97,end:122},{type:"n",start:48,end:57},{type:"p",start:33,end:47},{type:"p",start:58,end:64},{type:"p",start:91,end:96},{type:"p",start:123,end:126}],cc;T(ja,{hankaku:function(a,b){return Jc(a,b,rg,"hankaku")},zenkaku:function(a,b){return Jc(a,b,Be,"zenkaku")},hiragana:function(a,b){!1!==b&&(a=Jc(a,"k",Be,"zenkaku"));return a.replace(/[\u30A1-\u30F6]/g,function(c){return X(c.charCodeAt(0)+-96)})},katakana:function(a){return a.replace(/[\u3041-\u3096]/g,
function(b){return X(b.charCodeAt(0)+96)})}});(function(){Wa(ja,ug,function(a,b){var c=RegExp("^["+b.src+"\\s]+$"),d=RegExp("["+b.src+"]");D(ua(b.name),function(e){a["is"+e]=function(f){return c.test(f.trim())};a["has"+e]=function(f){return d.test(f.trim())}})})})();(function(){function a(d,e,f){b("zenkaku",d,e,f);b("hankaku",d,f,e)}function b(d,e,f,g,h){var k=cc[d][f]||{};!1!==h&&(k.all=g);k[e]=g;cc[d][f]=k}var c;cc={zenkaku:{},hankaku:{}};D(vg,function(d){Kb(d.end-d.start+1,function(e){e+=d.start;
a(d.type,X(e),X(e+65248))})});(function(){for(var d=0;57>d;d++){var e="\u30a2\u30a4\u30a6\u30a8\u30aa\u30a1\u30a3\u30a5\u30a7\u30a9\u30ab\u30ad\u30af\u30b1\u30b3\u30b5\u30b7\u30b9\u30bb\u30bd\u30bf\u30c1\u30c4\u30c3\u30c6\u30c8\u30ca\u30cb\u30cc\u30cd\u30ce\u30cf\u30d2\u30d5\u30d8\u30db\u30de\u30df\u30e0\u30e1\u30e2\u30e4\u30e3\u30e6\u30e5\u30e8\u30e7\u30e9\u30ea\u30eb\u30ec\u30ed\u30ef\u30f2\u30f3\u30fc\u30fb".charAt(d);c="\uff71\uff72\uff73\uff74\uff75\uff67\uff68\uff69\uff6a\uff6b\uff76\uff77\uff78\uff79\uff7a\uff7b\uff7c\uff7d\uff7e\uff7f\uff80\uff81\uff82\uff6f\uff83\uff84\uff85\uff86\uff87\uff88\uff89\uff8a\uff8b\uff8c\uff8d\uff8e\uff8f\uff90\uff91\uff92\uff93\uff94\uff6c\uff95\uff6d\uff96\uff6e\uff97\uff98\uff99\uff9a\uff9b\uff9c\uff66\uff9d\uff70\uff65".charAt(d);
a("k",c,e);e.match(sg)&&a("k",c+"\uff9e",X(e.charCodeAt(0)+1));e.match(tg)&&a("k",c+"\uff9f",X(e.charCodeAt(0)+2))}})();(function(){for(var d=0;7>d;d++)a("p","\uff61\uff64\uff62\uff63\u00a5\u00a2\u00a3".charAt(d),"\u3002\u3001\u300c\u300d\uffe5\uffe0\uffe1".charAt(d))})();a("s"," ","\u3000");a("k","\uff73\uff9e","\u30f4");a("k","\uff66\uff9e","\u30fa");b("hankaku","n","\u2212","-");b("hankaku","n","\u30fc","-",!1);b("zenkaku","n","-","\uff0d",!1)})();C.Date.addLocale("fr",{plural:!0,units:"milliseconde:|s,seconde:|s,minute:|s,heure:|s,jour:|s,semaine:|s,mois,an:|s|n\u00e9e|nee",
months:"janv:ier|,f\u00e9vr:ier|+fevr:ier|,mars,avr:il|,mai,juin,juil:let|,ao\u00fbt,sept:embre|,oct:obre|,nov:embre|,d\u00e9c:embre|+dec:embre|",weekdays:"dim:anche|,lun:di|,mar:di|,mer:credi|,jeu:di|,ven:dredi|,sam:edi|",numerals:"z\u00e9ro,un:|e,deux,trois,quatre,cinq,six,sept,huit,neuf,dix",tokens:"l'|la|le,er","short":"{dd}/{MM}/{yyyy}",medium:"{d} {month} {yyyy}","long":"{d} {month} {yyyy} {time}",full:"{weekday} {d} {month} {yyyy} {time}",stamp:"{dow} {d} {mon} {yyyy} {time}",time:"{H}:{mm}",
past:"{sign} {num} {unit}",future:"{sign} {num} {unit}",duration:"{num} {unit}",timeMarkers:"\u00e0",ampm:"am,pm",modifiers:[{name:"day",src:"hier",value:-1},{name:"day",src:"aujourd'hui",value:0},{name:"day",src:"demain",value:1},{name:"sign",src:"il y a",value:-1},{name:"sign",src:"dans|d'ici",value:1},{name:"shift",src:"derni:\u00e8r|er|\u00e8re|ere",value:-1},{name:"shift",src:"prochain:|e",value:1}],parse:["{months} {year?}","{sign} {num} {unit}","{0?} {unit:5-7} {shift}"],timeParse:["{day|weekday} {shift?}",
"{weekday?},? {0?} {date}{1?} {months}\\.? {year?}"],timeFrontParse:["{0?} {weekday} {shift}","{weekday?},? {0?} {date}{1?} {months}\\.? {year?}"]})}).call(this);


Sugar.extend();

console.log(Date.getAllLocales());

(function($){$.fn.replaceText=function(b,a,c){return this.each(function(){var f=this.firstChild,g,e,d=[];if(f){do{if(f.nodeType===3){g=f.nodeValue;e=g.replace(b,a);if(e!==g){if(!c&&/</.test(e)){$(f).before(e);d.push(f)}else{f.nodeValue=e}}}}while(f=f.nextSibling)}d.length&&$(d).remove()})}})(jQuery);

jQuery(document).ready(function($){
    
    var default_format = "{dd}/{MM}/{yyyy}";
	
	
    var html = document.body.innerHTML;
    var newTxt = html.split('[#');

    for (var i = 1; i < newTxt.length; i++) {
        var format = default_format;
        var tag    = newTxt[i].split(']')[0];
        var parts  = tag.split(':');

        if (parts.length > 1) {
            format = parts[1];
        } else {
            format = default_format;
        }

        var d     = Date.create(parts[0]);
        var regex = "\\[#" + tag +  "]";
        var re    = new RegExp(regex, "g");
		
	  var dFrench = Sugar.Date.long(d, 'fr');
        console.log(dFrench);
				console.log( d.format(format, 'fr'));
				

        $('body *').replaceText(re, d.format(format, 'fr'));
    }
});